### ISSUE TITLE
coreos-install with cloud-config does not accept authorized key, if...

### ISSUE THREAD

**Issue by cons0l3** [coreos/bugs#1119]
Dear all,

I use a cloud-config during local install coreos-install -d /dev/sda -c local-cloud-config.yml with the following content:
```
#cloud-config
coreos:
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC...<EOF>
```

_Mind you, the ssh-rsa entry is not terminated by a new line, but is directly the end of the file._ During the coreos-install process the /var/lib/coreos-install/user_data file is sucessfully generated, but also has no newline at the end (it is 100% identical to the cloud-config file).

**The boot process fails to write /home/core/.ssh/authorized_keys.**

If I add a newline to the end of either the cloud_config during install or the user_data file, I will get a correctly working .ssh/authorized_keys file.

Maybe something can either be fixed during install or boot. Or give us a hint in the documentation.

Cheers
Carsten
