### ISSUE TITLE
ExecStart can't be overrided by drop-ins

### ISSUE THREAD

**Issue by xxyztwz** [coreos/bugs#1124]
When I use this config, everything is OK:
```
units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network":"10.1.0.0/16" }'
      command: start
```
But When I want to override `ExecStart` args, the logs shows:
`Feb 18 05:31:16 flannel-3.novalocal systemd[1]: flanneld.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.`

That's My config:
```
units:
    - name: flanneld.service
      drop-ins:
        - name: 10-docker-image.conf
          content: |
            [Service]
            ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
              /usr/bin/docker run --net=host --privileged=true --rm \
              --volume=/run/flannel:/run/flannel \
              --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
              --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
              --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
              --env-file=${FLANNEL_ENV_FILE} \
              --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
              --volume=${ETCD_SSL_DIR}:/etc/ssl/etcd:ro \
              docker.aaa.com.cn/flannel:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network":"10.1.0.0/16" }'
      command: start
```
Did I use the wrong configuration, or bugs?

CoreOS 835.12.0 Stable
