### ISSUE TITLE
nameservers.network It causes problems in an hour after the start

### ISSUE THREAD

**Issue by Energy1190** [coreos/bugs#1133]
Hi.

Сonfig file looks:

```
#cloud-config
users:
    - name: ****
      groups:
        - sudo
        - docker
        - systemd-journal
        - wheel
      passwd: ****
      ssh-authorized-keys:
        - ssh-rsa ****
coreos:
   update:
      reboot-strategy: off
      group: stable   
      units:
      - name: nameservers.network
        runtime: true
        content: |
          [Network]
          DNS=8.8.4.4
          DNS=209.244.0.3
          DNS=8.8.8.8

```

One hour after starting depending on a hypervisor problems. Xen simply reloaded. VirtualBox loses network. Physical machine loses / increases response time to queries related to the DNS. It happens at a stable channel and beta channel. It happens if you specify more than two DNS.

**Comment by orbistertius** [comment]
I may be wrong, but are you sure your cloud-config is valid? In the "coreos" section, "units" should have the same indentation of "update" because in YML spaces are meaningful:

```
#cloud-config
users:
    - name: foo
      groups:
        - sudo
        - docker
        - systemd-journal
        - wheel
      passwd: bar
      ssh-authorized-keys:
        - ssh-rsa bazzzfshkjfshjfgsjhfgsjfgj
coreos:
   update:
      reboot-strategy: off
      group: stable   
   units:
      - name: nameservers.network
        runtime: true
        content: |
          [Network]
          DNS=8.8.4.4
          DNS=209.244.0.3
          DNS=8.8.8.8
```

This cloud-config will pass the [Cloud-Config Validator](https://coreos.com/validate/) (provided  **** are replaced with dummy values in "name", "password", and "ssh-authorized-keys"), while yours will not.
