### ISSUE TITLE
resolv.conf is emptied few seconds after boot with static networking

### ISSUE THREAD

**Issue by basvdlei** [coreos/bugs#1140]
Since our beta machines have been upgraded to 899.8.0, the DNS servers entries disappear from /etc/resolv.conf a few seconds after boot.

We are running with a static networking setup as described [here](https://coreos.com/os/docs/latest/network-config-with-networkd.html#static-networking).

Sample from cloudconfig:
```yml
write_files:
- path: /etc/systemd/network/static.network
  permissions: "0644"
  content: |
    [Match]
    Name=en*

    [Network]
    Address=172.21.40.112/23
    Gateway=172.21.41.254
    DNS=171.21.99.200
    DNS=171.21.99.201
coreos:
  units:
  - name: systemd-networkd.service
    command: start
```

It seems the fix https://github.com/coreos/systemd/pull/30 for https://github.com/coreos/bugs/issues/1081 broke static networking setups. Apparently systemd-resolved uses the state files for updating resolv.conf.

Systemd-networkd stops a few seconds after boot because there are no DHCP leases (this 'feature' was introduced in v219, networkd stops when idle.) When restarting systemd-networkd.server the resolv.conf is correctly updated, but emptied again a few seconds later.
