### ISSUE TITLE
How to run AUFS on CoreOS stable? 

### ISSUE THREAD

**Issue by reiz** [coreos/bugs#1142]
Currently on the CoreOS stable channel (835.13.0) Docker runs by default with the storage driver overlay. How can I replace overlay through AUFS?

**Comment by orbistertius** [comment]
Maybe you could use a cloud-config like this one?

```
#cloud-config

coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 10-aufs-storage-driver.conf
          content: |
            [Service]
            Environment="DOCKER_OPTS=--storage-driver=aufs"
      command: start
```
