### ISSUE TITLE
locksmith with reboot-strategy off doesn't remove lock

### ISSUE THREAD

**Issue by wkruse** [coreos/bugs#1219]
``` yaml
coreos:
  update:
    group: stable
    reboot-strategy: off
```

I used the coreos/locksmith#94 as systemd drop-in

``` yaml
units:
  - name: locksmithd.service
    drop-ins:
    - name: 10-fix-race-condition.conf
      content: |
        [Unit]
        Requires=update-engine.service
        After=update-engine.service user-config.target system-config.target
```

to make

```
Failed Units: 1
  locksmithd.service
```

go away. It fixed it. But when I reboot with `locksmithctl reboot`, the lock is not removed. Is it a bug?

The new and undocumented

``` yaml
 locksmith:
    window_start: "Fri 02:00"
    window_length: "2h"
```

is cool, but afaik it doesn't support date/time expressions like `Mon-Fri *-*-* 02:00:00`.

```
NAME=CoreOS
ID=coreos
VERSION=899.15.0
VERSION_ID=899.15.0
BUILD_ID=2016-04-05-1035
PRETTY_NAME="CoreOS 899.15.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by wkruse** [comment]
With `reboot-strategy` set to `off`, `coreos-cloudinit` masks `locksmithd.service`, so it never runs. The [Auto-Updates with a Maintenance Window](https://coreos.com/os/docs/latest/update-strategies.html#auto-updates-with-a-maintenance-window) seems to miss the bit about **unlocking** after a successful reboot?

```
locksmithctl help reboot
NAME:
	reboot - Reboot honoring reboot locks.

USAGE:
	locksmithctl reboot

DESCRIPTION:
	Reboot will attempt to reboot immediately after taking a reboot lock. The user is responsible for unlocking after a successful reboot.
```

**Comment by wkruse** [comment]
The missing bit to unlock after successful reboot.

```yaml
  - name: unlock-after-reboot.service
    runtime: true
    content: |
      [Unit]
      Description=Unlock after successful reboot

      [Service]
      ExecStart=-/usr/bin/locksmithctl unlock
  - name: unlock-after-reboot.timer
    runtime: true
    command: start
    content: |
      [Unit]
      Description=Unlock after reboot timer

      [Timer]
      OnBootSec=10min
```

**Comment by crawford** [comment]
When the reboot strategy is set to `off` locksmith doesn't consult etcd at all, so it's expected that it won't unlock after a successful boot. Likewise, `locksmithctl reboot` shouldn't attempt to take the reboot lock when the strategy is `off`. If it is, then there is a bug.

**Comment by wkruse** [comment]
```
CoreOS stable (899.15.0)
Update Strategy: No Reboots
```

```yaml
coreos:
  update:
    group: stable
    reboot-strategy: off
```

```
● locksmithd.service
   Loaded: masked (/dev/null)
   Active: inactive (dead)
```

```
$ etcdctl get coreos.com/updateengine/rebootlock/semaphore
{"semaphore":1,"max":1,"holders":[]}
```

```
$ cat /etc/machine-id
85501f4a670a4b639ada453f34c9ec01
```

```
$ sudo locksmithctl reboot
```

After reboot

```
$ etcdctl get coreos.com/updateengine/rebootlock/semaphore
{"semaphore":0,"max":1,"holders":["85501f4a670a4b639ada453f34c9ec01"]}
```

Seems like there is a bug.
