### ISSUE TITLE
cloud-config: enable base64/gzip encoding of unit contents

### ISSUE THREAD

**Issue by bkeroackdsc** [coreos/bugs#1255]
I'm running up against the 16KB limit for EC2 userdata, caused by a lot of complicated unit definitions in my cloud-config document.

It would be really nice if we could do something like the following to reduce file size:

```yaml
coreos:
  units:
    - name: foobar.service
      command: start
      encoding: "gzip+base64"
      content: |
        H4sIAKgdh1QAAwtITM5WyK1USMqvUCjPLMlQSMssS1VIya9KzVPIySwszS9SyCpNLwYARQFQ5CcAAAA=
```

If there's no objection I can put together a PR.
