### ISSUE TITLE
Flanneld TLS Certs Problems On 1010.5.0

### ISSUE THREAD

**Issue by dnuzzo** [coreos/bugs#1312]
Recently had pieces of our Kubernetes cluster update to 1010.5.0 and now I'm seeing an issue with flanneld not starting because it can't find the TLS certs anymore.

I have 3 workers in my cluster currently running flannel. Two remain on 899.17.0 and have flannel start up without issue using the following path configuration blocks for flannel passed in the Cloud Config:

```
  flannel:
    etcd-cafile: /etc/ssl/etcd/pangea.ca-chain.cert.pem
    etcd-certfile: /etc/ssl/etcd/pangea.infra.cert.pem
    etcd-keyfile: /etc/ssl/etcd/pangea.infra.key.pem
    etcd-endpoints: <redacted>
```

```
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd2.service

            [Service]
            ExecStartPre=/usr/bin/etcdctl --endpoint <redacted> --ca-file /etc/pangea/certs/pangea.ca-chain.cert.pem --cert-file /etc/pangea/certs/pangea.infra.cert.pem --key-file /etc/pangea/certs/pangea.infra.key.pem set /coreos.com/network/config '{"Network":"<redacted>", "Backend": {"Type": "vxlan"}}'
        - name: 50-environment.conf
          content: |
            [Service]
            Environment="ETCD_SSL_DIR=/etc/pangea/certs"
```

This cloud config has not changed, nor has the location of the certs, but the third worker, updated to 1010.5.9, throws the following error when trying to start flannel: 
`Failed to create SubnetManager: open /etc/ssl/etcd/pangea.infra.cert.pem: no such file or directory`

Did the ENV variable for ETCD_SSL_DIR change? Or is no longer being read properly? Am I missing something obvious?
