### ISSUE TITLE
improper home directory ownership after coreos-install

### ISSUE THREAD

**Issue by dspinhirne** [coreos/bugs#1490]
# Issue Report
## Bug

After installing to disk using coreos-install I am unable to log in via ssh. Debug revealed permission issue with home directory. Upon further investigation I noticed that the owner of the home director was '1000' instead of the actual user.   
### CoreOS Version

NAME=CoreOS
ID=coreos
VERSION=1010.6.0
VERSION_ID=1010.6.0
BUILD_ID=2016-06-28-0910
PRETTY_NAME="CoreOS 1010.6.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
### Environment

Private lab. Installed from ISO as VM on top of esx
### Reproduction Steps

Boot from ISO using configdrive. Here is the user portion of the cloud-config I am using:

``` yaml
users:
  - name: "dspinhirne"
    groups:
      - "sudo"
      - "rkt"
      - "wheel"
    ssh-authorized-keys:
      - xxxxx
  - name: "user1"
    passwd: "$1$Ik46k3zM$xw3E6ezANB1PpShkJSmQU."
    groups:
      - "sudo"
      - "rkt"
      - "wheel"
```

Note that there are 2 users: one for testing ssh and another for temporary troubleshooting which uses a hard set passwd of "password". On boot from ISO I see the following:

```
ls -la /home/
total 0
drwxr-xr-x  5 root       root       100 Jul 29 17:16 .
drwxrwxrwt 16 root       root       400 Jul 29 17:16 ..
drwxr-xr-x  3 core       core       120 Jul 29 17:16 core
drwxr-xr-x  3 dspinhirne dspinhirne  60 Jul 29 17:16 dspinhirne
drwxr-xr-x  2 user1      user1       40 Jul 29 17:16 user1
```

Note that at this point I am able to log in as dspinhirne using key based ssh.

I then install:

```
coreos-install -d /dev/sda -c /media/configdrive/openstack/latest/user_data
...
Installing cloud-config...
Success! CoreOS stable 1010.6.0 is installed on /dev/sda
```

After reboot I am unable to log in as dspinhirne, but I can log in as user1. Here are the perms on /home:

```
ls -la /home/
total 36
drwxr-xr-x  5 root root 4096 Jul 29 17:30 .
drwxr-xr-x 17 root root 4096 Jul 29 17:30 ..
drwxr-xr-x  3 core core 4096 Jun 28 09:15 core
drwxr-xr-x  3 1000 1000 4096 Jul 29 17:30 dspinhirne
drwxr-xr-x  3 1002 1002 4096 Jul 29 17:30 user1
```

I may ssh as dspinhirne only after correcting the ownership on /home/dspinhirne:
    `chown dspinhirne:dspinhirne /home/dspinhirne/`
