### ISSUE TITLE
XenServer Tools is unable to report CoreOS' VM IP address to parent XenServer after 1122.2.0 update

### ISSUE THREAD

**Issue by simoninkin** [coreos/bugs#1563]
# Issue Report #

## Bug ##

Basically, VM's XenServer Tools agent fails to register itself with host XenServer.
This means there is no IP address shown in Networking tab, resulting in inability to enable Docker management (along with any other functionality, when a connection from XenServer to VM is required), due to XenServer being unable to connect to host VM.

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

This issue has been tested with following CoreOS versions:

**1068.9.0** - _no issue_
**1068.10.0** - _no issue_
**1122.2.0** - _issue is present_

### Environment ###

XenServer 7
Applied update: XS70E004
Supplemental Packs:
 - BasePack (version 2.1.0)
 - XenServer Pack (version 7.0.0)
 - XSContainer Management (version 7.0.0-125372c)

XenCenter version 7.0 (build 7.0.1.3852) 64-bit

XenOrchestra (from sources):
 - xo-server 5.1.6
 - xo-web 5.1.9

### Expected Behavior ###

CoreOS boots
XenServer Tools agent starts - no errors
XenCenter shows 'Virtualization state: Optimized (version 7.0 installed)' in VM's General tab
XenCenter shows IP address(es) related to VM in Networking tab
XenCenter is able to turn on Docker management via an SSH connection

### Actual Behavior ###

CoreOS boots
XenServer Tools agent starts - no errors
XenCenter shows 'Virtualization state: Optimized (version 6.2 installed)' in VM's General tab
XenCenter missing IP address(es) related to VM in Networking tab
XenCenter is not able to turn on Docker management via an SSH connection. Failing due to missing IP address.

### Reproduction Steps ###

  1. Boot CoreOS from ISO image with a default XenOrchestra cloud-config
  2. Open XenCenter, navigate to VM's Networking tab

### Other Information ###

Cloud config template from XenOrchestra:

```
#cloud-config

hostname: %VMNAMETOHOSTNAME%
ssh_authorized_keys:
  # - ssh-rsa <Your public key>
  # The following entry will automatically be replaced with a public key
  # generated by container management plugin. The key-entry must exist,
  # in order to enable container management for this VM.
  - ssh-rsa %CONTAINERRSAPUB%
coreos:
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    # Hypervisor Linux Guest Agent
    - name: xe-linux-distribution.service
      command: start
      content: |
        [Unit]
        Description=Hypervisor Linux Guest Agent
        After=docker.service

        [Service]
        ExecStartPre=/media/configdrive/agent/xe-linux-distribution /var/cache/xe-linux-distribution
        ExecStart=/media/configdrive/agent/xe-daemon
  etcd:
    name: %VMNAMETOHOSTNAME%
    # generate a new token for each unique cluster at https://discovery.etcd.io/
new
    # discovery: https://discovery.etcd.io/<token>
write_files:
  # Enable ARP notifications for smooth network recovery after migrations
  - path: /etc/sysctl.d/10-enable-arp-notify.conf
    permissions: 0644
    owner: root
    content: |
      net.ipv4.conf.all.arp_notify = 1
```
