### ISSUE TITLE
Ignition boot gets stuck when using multiple disks

### ISSUE THREAD

**Issue by razvanm** [coreos/bugs#1571]
# Issue Report #

## Bug ##

Using multiple disks make Ignition booting to stuck saying `A start job is running for Ignition (disks) ([...] / no limit)`. The issue doesn't happen when the list of disks is only one but it can happen even for a small number of disks (even two).

These is the exact setting I'm using for a SuperMicro server with 2 SSDs and 6 HDDs.

```
storage:
  disks:
    - device: "/dev/nvme0n1"
      wipe_table: true
      partitions:
        - label: "ssd0"
          number: 0
    - device: "/dev/nvme1n1"
      wipe_table: true
      partitions:
        - label: "ssd1"
          number: 0
    - device: "/dev/sda"
      wipe_table: true
      partitions:
        - label: "ata.1"
          number: 0
    - device: "/dev/sdb"
      wipe_table: true
      partitions:
        - label: "ata.2"
          number: 0
    - device: "/dev/sdc"
      wipe_table: true
      partitions:
        - label: "ata.3"
          number: 0
    - device: "/dev/sdd"
      wipe_table: true
      partitions:
        - label: "ata.4"
          number: 0
    - device: "/dev/sde"
      wipe_table: true
      partitions:
        - label: "ata.5"
          number: 0
    - device: "/dev/sdf"
      wipe_table: true
      partitions:
        - label: "ata.6"
          number: 0
```

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

Same thing happen also on the current CoreOS beta (1153.0.0) and CoreOS alpha (1164.1.0).

### Environment ###

Bare metal using a SuperMicro server.

### Expected Behavior ###

The boot should not get stuck.

### Actual Behavior ###

The boot gets stuck.

### Reproduction Steps ###

  1. Use an Ignition config with multiple disks.
  2. Attempt to boot the above config.
