### ISSUE TITLE
Machine rebooted though we configured reboot-strategy: off

### ISSUE THREAD

**Issue by zeisss** [coreos/bugs#161]
Hi

this morning one of our nodes rebooted and updated from 402 to 457 with a reboot. 

We have disabled reboots in the cloud-init though:

```
#cloud-config

coreos:
  update:
    reboot-strategy: off

  <more config>
```

`/etc/coreos/update.conf` says the same:

```
# cat /etc/coreos/update.conf
GROUP=alpha
REBOOT_STRATEGY=off
```
