### ISSUE TITLE
CoreOS on AWS EC2 won't get private ip after reboot/update, if docker.service is stated via cloud-config

### ISSUE THREAD

**Issue by yellowmegaman** [coreos/bugs#1635]
# Issue Report #
CoreOS on AWS EC2 won't get private ip after reboot/update, if docker.service is stated via cloud-config

## Bug ##
Launched coreos cluster with cloud-config on ec2.
Cloud config - http://pastebin.com/raw/mZjzbMwB
docker command start is cornerstone here. If specified, instance won't get privip after reboot. If i specify some container, e.g. redis.service instead of specifying docker.service, everything will be ok.

### CoreOS Version ###
1068.10.0 / 1122.3.0 / beta channel

$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.10.0
VERSION_ID=1068.10.0
BUILD_ID=2016-08-23-0220
PRETTY_NAME="CoreOS 1068.10.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"

### Environment ###
AWS EC2 us-east-1d HVM/PV

### Expected Behavior ###
CoreOS should just reboot and get ip normally. E.g.:
After reboot, if i choose "get instance screenshot" i should see:
SSH host keys
eth0: privip ipv6

### Actual Behavior ###
After reboot, if i choose "get instance screenshot" i see:
SSH host keys
eth0: ipv6

### Reproduction Steps ###

  1. Start coreos on EC2 with docker.server command: start in cloud config
  2. Reboot / locksmith update

### Other Information ###
AWS ami's used: 
1) ami-9c086a8b from aws marketplace
2) ami-bf5605a8 ami-7e4f1c69 ami-40570457 from coreos docs

Thanks a lot in advance!

**Comment by crawford** [comment]
> CoreOS on AWS EC2 won't get private ip after reboot/update

Is this only seen via the login issue (the screenshot text you describe), or does it actually affect the networking?

**Comment by yellowmegaman** [comment]
No network at all, no ping/ssh/telnet etcetera.

**Comment by mischief** [comment]
@yellowmegaman can you simply not 'start' docker? anything that needs it should be able to socket-activate it.

**Comment by yellowmegaman** [comment]
Actually, i don't have a need to start-only docker. Just thought that it can be leading to other bugs, since network completely breaks after this configuration. If you consider that minor, or rare-case please close.

**Comment by monder** [comment]
Seems interesting issue, but unfortunately I was unable to reproduce it. Is it only after reboot, and does not happen on the first boot? Maybe there are some units in fleet that are messing up the instance?

**Comment by yellowmegaman** [comment]
Fresh-launched coreos with cloud-config posted above - http://pastebin.com/raw/mZjzbMwB. Nothing else. Cluster of 3-4 machines, IIRC even one machine - same behaviour.

**Comment by crawford** [comment]
I successfully booted and rebooted CoreOS-stable-1122.3.0-hvm (ami-17064d77) with the following config:

```yaml
#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  locksmith:
    window-start: Wed 04:00
    window-length: 1h
  units:
    - name: docker.service
      command: start
```

@yellowmegaman is this enough to trigger the failure in your environment?

**Comment by yellowmegaman** [comment]
@crawford Config above working great, not problems caused by reboot. Tried on single node, 1068.10.0 / ami-9c086a8b. So it must be an option config in my submitted cloud-config.

**Comment by crawford** [comment]
I'm guessing you are scheduling something with fleet which is causing the issue. The rest of your config is fine and is known to work.

**Comment by yellowmegaman** [comment]
Tell you what, i'm just starting with coreos, was using successfully flannel + etcd + consul on debian. And  didn't even begin messing with fleet. Config posted above, with docker.service removed, failed also when i just docker run'd cassandra container. All nodes disconnected, rebooted and no network.

Gona try different ami / coreos version and region and write back all steps.

**Comment by crawford** [comment]
If you can write down step-by-step what you are running, I can try to figure out what is going on. I'm not 100% certain I understand what's happening yet.

As a side note, if you are just getting started with fleet, I would suggest looking at kubernetes instead. We are investing resources in that project instead of fleet at this point and the plan is to retire fleet in the not-to-distant future. I would hate to see you invest time and energy only to see that the project is being killed.

**Comment by yellowmegaman** [comment]
Great many thanks for advice about kubernetes. Time indeed is valuable resource.
I've put everything to terraform script to simplify reproducing.

Hope this log isn't ugly. http://pastebin.com/p4tJP5K3

Some screenshots. First one is coreos1 after reboot. Second and third - coreos2 before and after reboot respectively.

![coreos01](https://cloud.githubusercontent.com/assets/3943191/19905477/ff94c0e0-a087-11e6-841f-c599ee9ad666.png)
![coreos02](https://cloud.githubusercontent.com/assets/3943191/19905479/0214551a-a088-11e6-9a26-999be139d594.png)
![coreos02-after-reboot](https://cloud.githubusercontent.com/assets/3943191/19905484/03e0a01a-a088-11e6-9a5f-dd056dece2bc.png)

**Comment by crawford** [comment]
Weird. I was able to repro it with the following config:

```yaml
#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  locksmith:
    window-start: Wed 04:00
    window-length: 1h
  fleet:
    public-ip: "$public_ipv4"
  flannel:
    etcd_prefix: "/coreos.com/network2"
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network2/config '{"Network": "10.0.0.0/8", "SubnetLen": 20, "SubnetMin": "10.10.0.0", "SubnetMax": "10.99.0.0", "Backend": { "Type": "vxlan"}}'
      command: start
    - name: nameservers.network
      content: |
        [Network]
        DNS=8.8.8.8
```

**Comment by yellowmegaman** [comment]
Don't know what's happening anymore. Just booted another cluster and rebooted straight away - same result - total loss of connectivity. Same ami/region

**Comment by crawford** [comment]
I'm trying to narrow down that config to figure out what is going on. It looks like an interaction between fleet and flannel (testing on 1185.3.0).

**Comment by yellowmegaman** [comment]
Removing fleet.service didn't help, soo ...

**Comment by crawford** [comment]
This appears to be the minimal repro case (single node):

```yaml
#cloud-config

coreos:
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network": "10.0.0.0/8", "Backend": { "Type": "vxlan"}}'
      command: start
```

If I don't start flannel or fleet, it reboots fine. If I change the flannel backend to UDP, it reboots fine.
