### ISSUE TITLE
CoreOS reboots when using shared mounts and Flannel is running

### ISSUE THREAD

**Issue by rul** [coreos/bugs#1658]
# Issue Report #

## Bug ##

When running Flannel, there is a limited amount of `shared` mounts that one can do before the system hangs completely, with several process running at 100% CPU and memory being consumed by them, eventually invoking OOM or crashing and rebooting the whole system.

### CoreOS Version ###

```
cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

I've also tried this on CoreOS version 1122.3.0 and the bug was there. It can probably be found on earlier versions.

### Environment ###

I detected for the first time on Baremetal servers, and then was able to reproduce it on a Vagrant machine using VirtualBox as a provider.

### Expected Behavior ###

The expected behavour is to run Docker with shared mounts without crashing the whole system.

### Actual Behavior ###

This happens only while Flannel is running. If it's running under **rkt**, then the amount of shared mounts I can do with Docker is one. The second one will hang the server. If it's running under **Docker**, then I can do around seven or eight mounts before the system misbehaves.

The behavior is different if Flannel is running with Docker or rkt. With rkt, appereantly we're hit by bug #1612 and tons of mounts are created:

```
# cat /proc/mounts | wc -l
166055
```

They're basically like this:

```
cgroup /sys/fs/cgroup/systemd/docker/a1916967b7f29d764bea3fbeffa4c6752f735d5ed9a3c13bcc4f315bb9403c67 cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /var/lib/rkt/pods/run/34bb9083-6092-4172-8c8b-ffe9397cdd8b/stage1/rootfs/opt/stage2/flannel/rootfs/sys/fs/cgroup/systemd/docker/a1916967b7f29d764bea3fbeffa4c6752f735d5ed9a3c13bcc4f315bb9403c67 cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /var/lib/rkt/pods/run/1bec60bc-8c5a-43e6-a6d3-5c277eeb7c56/stage1/rootfs/opt/stage2/flannel/rootfs/sys/fs/cgroup/systemd/docker/a1916967b7f29d764bea3fbeffa4c6752f735d5ed9a3c13bcc4f315bb9403c67 cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/systemd/docker/a1916967b7f29d764bea3fbeffa4c6752f735d5ed9a3c13bcc4f315bb9403c67 cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /var/lib/rkt/pods/run/34bb9083-6092-4172-8c8b-ffe9397cdd8b/stage1/rootfs/opt/stage2/flannel/rootfs/sys/fs/cgroup/systemd/docker/a1916967b7f29d764bea3fbeffa4c6752f735d5ed9a3c13bcc4f315bb9403c67 cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /var/lib/rkt/pods/run/1bec60bc-8c5a-43e6-a6d3-5c277eeb7c56/stage1/rootfs/opt/stage2/flannel/rootfs/sys/fs/cgroup/systemd/docker/a1916967b7f29d764bea3fbeffa4c6752f735d5ed9a3c13bcc4f315bb9403c67 cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
```

Then the OOM goes berserker, as can be seen in [this trace](https://gist.github.com/rul/e404e86da33f35199c70a6ad75f9fee6).

If Flannel is running under Docker, we can run around seven to twelve containers before the Docker daemon becomes unresponsive. Note that in this case there is no resource exhaustion and I couldn't find any logs that provides a lead on what's going on.

Finally, if I try to run containers with shared mounts without Flannel running, I can have running as many containers as I want.

### Reproduction Steps ###

I've prepared three cloud-configs files that can be used to reproduce this scenarios using the
[coreos-vagrant](https://github.com/coreos/coreos-vagrant) repository. Once that you have the VM running, you can easily try the shared mounts with Docker by doing something like this: `docker run  -d  -v /mnt:/mnt:shared --privileged   nginx`

1. user-data with Flannel running on rkt

```
#cloud-config

coreos:
  flannel:
    interface: $public_ipv4
  units:
    - name: docker.service
      command: start
      drop-ins:
      - name: 10-mount-shared.conf
        content: |
          [Service]
          MountFlags=shared
    - name: etcd2.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
      - name: 50-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
```

2. user-data with Flannel running on Docker
I've used the Flannel systemd unit file from CoreOS 1068.10.0.

```
#cloud-config

coreos:
  flannel:
    interface: $public_ipv4
  units:
    - name: docker.service
      command: start
      drop-ins:
      - name: 10-mount-shared.conf
        content: |
          [Service]
          MountFlags=shared
    - name: etcd2.service
      command: start
    - name: flanneld.service
      command: start
      content: |
        [Unit]
        Description=Network fabric for containers
        Documentation=https://github.com/coreos/flannel
        Requires=early-docker.service
        After=etcd.service etcd2.service early-docker.service
        Before=early-docker.target

        [Service]
        Type=notify
        Restart=always
        RestartSec=5
        Environment="TMPDIR=/var/tmp/"
        Environment="DOCKER_HOST=unix:///var/run/early-docker.sock"
        Environment="FLANNEL_VER=0.5.5"
        Environment="FLANNEL_IMG=quay.io/coreos/flannel"
        Environment="ETCD_SSL_DIR=/etc/ssl/etcd"
        Environment="FLANNEL_ENV_FILE=/run/flannel/options.env"
        LimitNOFILE=40000
        LimitNPROC=1048576
        ExecStartPre=/sbin/modprobe ip_tables
        ExecStartPre=/usr/bin/mkdir -p /run/flannel
        ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR}
        ExecStartPre=-/usr/bin/touch ${FLANNEL_ENV_FILE}

        ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
        /usr/bin/docker run --net=host --privileged=true --rm \
        --volume=/run/flannel:/run/flannel \
        --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
        --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
        --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
        --env-file=${FLANNEL_ENV_FILE} \
        --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
        --volume=${ETCD_SSL_DIR}:${ETCD_SSL_DIR}:ro \
        ${FLANNEL_IMG}:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true

        # Update docker options
        ExecStartPost=/usr/bin/docker run --net=host --rm --volume=/run:/run \
        ${FLANNEL_IMG}:${FLANNEL_VER} \
        /opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i

        [Install]
        WantedBy=multi-user.target
      drop-ins:
      - name: 50-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
```

3. user-data with no running instance of Flannel

```
#cloud-config

coreos:
  flannel:
    interface: $public_ipv4
  units:
    - name: docker.service
      command: start
      drop-ins:
      - name: 10-mount-shared.conf
        content: |
          [Service]
          MountFlags=shared
    - name: etcd2.service
      command: start
```

### Other Information ###

I've noticed that when the Flannel-rkt combination is running on bare-metal, the machine just dies and reboots, whereas in the VM the OOM just starts killing processes.
