### ISSUE TITLE
GCE boot fails with parsing error.

### ISSUE THREAD

**Issue by rafroehlich2** [coreos/bugs#171]
Following the guide provided on CoreOS docs for booting a GCE instance results in the following.

```
CoreOS (stable)
Failed Units: 1
  gce-coreos-cloudinit.service

systemctl status gce-coreos-cloudinit.service
   gce-coreos-cloudinit.service
   Loaded: loaded (/run/systemd/system/gce-coreos-cloudinit.service; static)
   Active: failed (Result: exit-code) since Wed 2014-10-22 19:02:30 UTC; 8min ago
  Process: 763 ExecStart=/usr/share/oem/bin/gce-coreos-cloudinit (code=exited, status=1/FAILURE)
 Main PID: 763 (code=exited, status=1/FAILURE)
```

Running `gce-coreos-cloudinit` results in

```
Trying to fetch project user-data...
curl: (22) The requested URL returned error: 404 Not Found
project user-data is missing or empty, skipping
Trying to fetch instance user-data...
Checking availability of "local-file"
Fetching user-data from datasource of type "local-file"
Fetching meta-data from datasource of type "local-file"
Failed to parse user-data: Unrecognized user-data header: #cloud-config  coreos:   etcd:     discovery: https://dis
covery.etcd.io/fa66cf30f2a...     addr: :4001     peer-addr: :7001   units:     - name: etcd.serv
ice       command: start     - name: fleet.service       command: start
Continuing...
No cloud-config data to handle.
```

The cloud-config.yml looks like this

```
#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/fa66cf30f2a...
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
```
