### ISSUE TITLE
Can't turn off autoupdating

### ISSUE THREAD

**Issue by argent-smith** [coreos/bugs#1798]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.9.0
VERSION_ID=1235.9.0
BUILD_ID=2017-02-02-0235
PRETTY_NAME="Container Linux by CoreOS 1235.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

It's generic install on VMs under ProxMox

### Expected Behavior ###

When following https://coreos.com/os/docs/latest/update-strategies.html and setting these in userconfig:

```
coreos:
  units:
    - name: update-engine.service
      command: stop
      enable: false
    - name: locksmithd.service
      command: stop
      enable: false
```

I expect that the OS wouldn't autoupdate and the corresponding systemd services are in stopped and disabled state.

### Actual Behavior ###

The units are in enabled/running state, the OS has autoupdated.

### Reproduction Steps ###

  1. install ContainerLinux 1235.6.0, follow the cited manual and set the units configuration in the user-config as described
  2. reboot
  3. after a day, see it autoupdated
