### ISSUE TITLE
container-linux-config-transpiler: fails to create files 

### ISSUE THREAD

**Issue by drywheat** [coreos/bugs#1837]
# Issue Report #

### CT Version ###

`ct v0.1.0-5-g03ae4e1`

### Environment ###

OS: **macOS 10.12.1**
Go: **go version go1.8 darwin/amd64**

The `ct` binary was compiled using the source code at this commit: https://github.com/coreos/container-linux-config-transpiler/commit/03ae4e169a57cdaee9a639b8980e6d004d9d82c4

### Expected Behavior ###

In accordance with the [config spec](https://coreos.com/ignition/docs/latest/configuration.html), I would expect the following YAML to compile into JSON without an warnings/errors:

```yaml
#container-linux-config

storage:
  files:
    - filesystem: "root"
      path: /etc/replicated.alias
      contents:
        source: "data:,alias%20replicated%3D%22sudo%20docker%20exec%20-it%20replicated%20replicated%22"
```

### Actual Behavior ###

The transpiler reports a warning ("Config has unrecognized key: source") and fails to pass my source data into the resultant JSON. Here's what gets generated:

```json
warning at line 7, column 8
Config has unrecognized key: source

{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/replicated.alias",
        "contents": {
          "source": "data:,",
          "verification": {}
        },
        "user": {},
        "group": {}
      }
    ]
  },
  "systemd": {},
  "networkd": {},
  "passwd": {}
}
```

### Reproduction Steps ###

  1. Build `ct` using the git commit listed above
  2. Pass the provided YAML contents to `ct` and watch it fail: `cat see-up-above.yml | ct`

### Other Information ###

If I take the JSON generated above and manually paste my URL encoded data into it, then two things happen:

1. The CoreOS config validator reports that it is valid.
2. Passing it to Ignition at boot time results in the file being created with the proper contents.

This all leads me to confidently believe the problem lies with `ct`.

**Comment by crawford** [comment]
The specification you are following is for Ignition. CT processes [Container Linux Configs](https://coreos.com/os/docs/latest/configuration.html). This is a little confusing right now because of how closely the two formats resemble one another, but this will change over time as we improve CT.

You actually want to write the following:

```yaml
storage:
  files:
    - filesystem: "root"
      path: /etc/replicated.alias
      contents:
        inline: |
          alias replicated="sudo docker exec -it replicated replicated"
```
