### ISSUE TITLE
 Docker stack deploy healthcheck in V3 docker-compose.yml not working in CoreOS Alpha 1339.0.0

### ISSUE THREAD

**Issue by pmualaba** [coreos/bugs#1848]
# Issue Report #

## Bug ##

The following command works perfectly in  CoreOS Alpha 1325.1.0 but it does not work anymore in CoreOS Alpha 1339.0.0

On executing the following command in the latest CoreOS Alpha 1339.0.0 I now receive the following error:

`    **.depends_on must be a list**`

 
`$ docker stack deploy neo4j-test --compose-file=./docker-compose.yml`

```
version: '3'

services:

  neo4j-999-601-test:
    image: neo4j:3.1.1
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j-test
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://neo4j-999-601-test:7474 && echo 'OK'"]
      interval: 5s
      timeout: 2s
      retries: 3
```

... in other container ... ; 

```
    depends_on:
      neo4j-999-601-test:
        condition: service_healty

```

V3 supports docker healthcheck `condition` parameter for `depends_on` directive. It seems that docker-compose.yml Version '3' format is not parsed correctly anymore?

 

### Container Linux Version ###
Alpha 1339.0.0
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Expected Behavior ###
healtcheck and depends_on condition used in V3 docker-compose.yml file should not give error

`    **.depends_on must be a list**`

when executing `docker stack deploy` in swarm mode.

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by crawford** [comment]
It looks like docker is complaining that the `depends_on` option you provided isn't a list (maybe they changed that recently). I think you actually want to use something like this:

```yaml
    depends_on:
      - neo4j-999-601-test:
          condition: service_healty [sic]
```
