### ISSUE TITLE
system clocksource defaulted to refined-jiffies

### ISSUE THREAD

**Issue by agokjr** [coreos/bugs#185]
Running on bare metal multiple desktop machines with clock was running ~5 times slow. After some poking around found the clock source was to blame.

/sys/devices/system/clocksource/clocksource0 $ cat available_clocksource 
refined-jiffies jiffies tsc 

/sys/devices/system/clocksource/clocksource0 $ cat current_clocksource 
refined-jiffies 

Solved the immediate problem by changing to tsc.
writing tsc to current_clocksource

~~Added this to my cloud config to try and make sure fix stays.~~

``` yaml
write_files:
  - path: /sys/devices/system/clocksource/clocksource0/current_clocksource
    content: tsc
```

However is there a reason to have it have it pick refined-jiffies over tsc by default when jiffies is effected by cpu power saving features. Or is it currently picking first item on list?

UPDATE: the write_file can not write to this location and will error.  See marineam post for work around.
