### ISSUE TITLE
Edit user in cloud-config.yml, remains the old one, why?

### ISSUE THREAD

**Issue by alisonbuss** [coreos/bugs#1882]
Hello everyone!

Guys, I have a question.

I installed **(coreos_production_iso_image-alpha-v1339.0.0.iso)** on a VirtualBox VM using [cloud-config.yaml](https://github.com/alisonbuss/Formulation/blob/master/cloud-config.yaml), perfect installation :-)

After the installation, I downloaded the file [vagrantfile-user-data](https://github.com/alisonbuss/Formulation/blob/master/vagrantfile-user-data) to the folder **(/var/lib/coreos-vagrant/vagrantfile-user-data)** and applied *"$ sudo reboot"*.

Everything perfect :-)

List user groups:
```
$ cat /etc/group
wheel:x:10:root,core
sudo:x:150:teste,vagrant
docker:x:233:core,teste,vagrant
systemd-coredump:x:998:
fleet:x:253:core
rkt:x:251:core
rkt-admin:x:999:
teste:x:200:
vagrant:x:1000:
```

**The problem is** when I edit the [vagrantfile-user-data](https://github.com/alisonbuss/Formulation/blob/master/vagrantfile-user-data), switching "teste" to "teste1" and applies *"$ sudo reboot"*, after rebooting the VM, the user "teste" still exists? :-(

```
$ cat /etc/group
wheel:x:10:root,core
sudo:x:150:teste,vagrant,teste1
docker:x:233:core,teste,vagrant,teste1
systemd-coredump:x:998:
fleet:x:253:core
rkt:x:251:core
rkt-admin:x:999:
teste:x:200:
vagrant:x:1000:
teste1:x:199:
```

**Example**
```
#cloud-config
users:
  - name: "teste"
    passwd: "$1$G5qGDBp7$BYrRnKuGMXFYaZojrQ02h/"
    groups:
      - "sudo"
      - "docker"
```
**For**
```
#cloud-config
users:
  - name: "teste1"
    passwd: "$1$G5qGDBp7$BYrRnKuGMXFYaZojrQ02h/"
    groups:
      - "sudo"
      - "docker"
```

**It gets worse**, if I edit the **"ssh_authorized_keys"** key the old one still remains active

**Example**
```
#cloud-config
ssh_authorized_keys:
  - "ssh-rsa AAAAAAAAA... vagrant insecure public key"
```
**For**
```
#cloud-config
ssh_authorized_keys:
  - "ssh-rsa BBBBBBBBB... user@pc-admin"
```          

**This is normal?**

**It's right?**

*Sorry for my english, it's translated by google translate, I'm brazilian, I do not speak english very well.*
