### ISSUE TITLE
ct: add flannel sugar for `ExecStartPre`'ing the flannel config into etcd

### ISSUE THREAD

**Issue by dgonyeo** [coreos/bugs#1888]
This is how you have to do it today:

```yaml
systemd:
  units:
    - name: flanneld.service
      dropins:
        - name: 50-network-config.conf
          contents: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
```

This is how you should be able to do it:

```yaml
flannel:
  config: |
    { "Network": "10.1.0.0/16" }
  ...
```
