### ISSUE TITLE
ct generates invalid etcd-member drop-ins

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1895]
# Issue Report #

## Bug ##

Given the following CLC:

```yaml
etcd:
  version:                     3.1.4
  advertise_client_urls:       http://${PUBLIC_IPV4}:2379 \
  initial_advertise_peer_urls: http://${PRIVATE_IPV4}:2380 \
  listen_client_urls:          http://0.0.0.0:2379 \
  listen_peer_urls:            http://${PRIVATE_IPV4}:2380 \
  discovery:                   https://discovery.etcd.io/<token>
```

ct generates the following `/etc/systemd/system/etcd-member.service.d/20-clct-etcd-member.conf`:

```ini
[Unit]
Requires=coreos-metadata.service
After=coreos-metadata.service

[Service]
EnvironmentFile=/run/metadata/coreos
Environment="ETCD_IMAGE_TAG=v3.1.4"
ExecStart=
ExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS \
  --listen-peer-urls="http://$${COREOS_DIGITALOCEAN_IPV4_PRIVATE_0}:2380 \\" \
  --listen-client-urls="http://0.0.0.0:2379 \\" \
  --initial-advertise-peer-urls="http://$${COREOS_DIGITALOCEAN_IPV4_PRIVATE_0}:2380 \\" \
  --advertise-client-urls="http://$${COREOS_DIGITALOCEAN_IPV4_PUBLIC_0}:2379 \\" \
  --discovery="https://discovery.etcd.io/<token>"
```

Notice the trailing `\` on several of the flags.
