### ISSUE TITLE
Feature: baremetal etcd2 ip discovery with $public_ipv4

### ISSUE THREAD

**Issue by dashesy** [coreos/bugs#1899]
# Issue Report #

etcd2 does not work with `$public_ipv4` substitution. I followed [here](https://coreos.com/os/docs/latest/nginx-host-cloud-config.html) and set up nginx

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Baremetal server

### Expected Behavior ###

etcd2 to work without having to enter static ip addresses.

### Actual Behavior ###

etcd2 does not work. `$public_ipv4` is substituted with `""` and it does not start. Unless the actual ip is added of course.

### Reproduction Steps ###

  1. Use `$public_ipv4` in the cloud-config
  2. Run `sudo coreos-cloudinit -from-file /var/lib/coreos-install/user_data`

### Other Information ###

This is how I set up Nginx (because the [docs](https://coreos.com/os/docs/latest/nginx-host-cloud-config.htm) do not have a fully working example)

```
    - name: nginx.service
      command: start
      content: |
        [Unit]
        Description=Nginx
        After=docker.service
        Requires=docker.service
        [Service]
        StandardOutput=journal
        StandardError=journal
        Restart=always
        ExecStartPre=-/usr/bin/docker stop nginx
        ExecStartPre=-/usr/bin/docker rm nginx
        ExecStart=/usr/bin/docker run --name nginx -p 8080:80 -p 8081:443 -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro -v /var/lib/coreos-install:/var/www/:ro --rm --name nginx nginx:1.11
        ExecStop-=/usr/bin/docker stop nginx
        RestartSec=10s
        [Install]
        WantedBy=multi-user.target
    - name: etcd2.service
      command: start
      drop-ins:
      - name: 60-etcd-wait-for-nginx-config.conf
        content: |
          [Unit]
          After=nginx.service
          Requires=nginx.service

          [Service]
          Restart=always
```

Together with

```
  - path: /etc/nginx/nginx.conf
    permissions: 0644
    owner: root:root
    content: |
        error_log /dev/stdout info;
        user  nginx;
        worker_processes  1;

        error_log  /var/log/nginx/error.log warn;
        pid        /var/run/nginx.pid;


        events {
            worker_connections  1024;
        }


        http {
            access_log /dev/stdout;
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;

            log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

            access_log  /var/log/nginx/access.log  main;

            sendfile        on;
            #tcp_nopush     on;

            keepalive_timeout  65;

            #gzip  on;

            include /etc/nginx/conf.d/*.conf;
            
            geo $dollar {
              default "$";
            }
            server {
              listen 8080;

              location ~ ^/user_data {
                root /var/www/;
                sub_filter '${dollar}public_ipv4' '$remote_addr';
                sub_filter '${dollar}private_ipv4' '$http_x_forwarded_for';
                # sub_filter '${dollar}private_ipv4' '$http_x_real_ip';
                sub_filter_once off;
                sub_filter_types '*';
              }
            }
        }
```

## Feature Request ##

Feature request for out of the box support for baremetal `$public_ipv4`

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Desired Feature ###

Out of the box support and documentation for bare metal

### Other Information ###

After struggling with it I realized since I have DNS set up I can use the `hostname` itself instead of the `$public_ipv4` and it works fine with `etcd2` too. 

So if you have set 

```
hostname: "mycoremachine1"
```

You can set up etcd2 like this:

```
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=1
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/some_uuid_you_got
    advertise-client-urls: http://mycoremachine1:2379,http://127.0.0.1:2379
    initial-advertise-peer-urls: http://mycoremachine1:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://mycoremachine1:2379,http://127.0.0.1:2379
    listen-peer-urls: http://mycoremachine1:2380
```

This should be fine for my case, but I feel there is little out-of-the-box support for baremetal.

**Comment by crawford** [comment]
> Feature request for out of the box support for baremetal `$public_ipv4`

coreos-cloudinit does not support variable substitution on baremetal. But why not? If we were to support it, which IP address would be the public address? Which one would be private?

A much better solution is to use Ignition and write your own IP-gathering logic. [The docs](https://coreos.com/ignition/docs/latest/metadata.html#custom-metadata-agent) give you an outline of the rough structure.

**Comment by dashesy** [comment]
I think a safe default would be the first ip address that is assigned: `hostname -i`. That at least will be useful for a class of bermetal scenarios (those that have a single outside-facing ip address).

Is ignition the new/better way to write cloud-config? That sounds like the solution, I wish I had started with ignition from the start.

**Comment by crawford** [comment]
> That at least will be useful for a class of bermetal scenarios (those that have a single outside-facing ip address).

And therein lies the problem. If the default doesn't work in the vast majority of cases, it is potentially a dangerous operation. You wouldn't want etcd to accidentally listen on a public interface which our tools thought was private. It's easier to force the user to make a decision when we aren't confident.

> Is ignition the new/better way to write cloud-config? That sounds like the solution, I wish I had started with ignition from the start.

Ignition is the preferred tool for provisioning instances of Container Linux. You can read more about it in [the docs](https://coreos.com/ignition/docs/latest/what-is-ignition.html).

**Comment by crawford** [comment]
I should have mentioned, `ct` and Ignition solve your issue by telling you upfront whether or not the variable is supported. For example:

Container Linux Config:

```yaml
etcd:
  # All options get passed as command line flags to etcd.
  # Any information inside curly braces comes from the machine at boot time.

  # multi_region and multi_cloud deployments need to use {PUBLIC_IPV4}
  advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  # listen on both the official ports and the legacy ports
  # legacy ports can be omitted if your application doesn't depend on them
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
  # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
  # specify the initial size of your cluster with ?size=X
  discovery:                   "https://discovery.etcd.io/<token>"
```

When I try to transpile the config, I get an error:

```
./ct < example.clc
error: platform must be specified to use templating
Generated Ignition config was invalid.
```

This is because ct needs to know which platform is going to be targeted so that it can use the correct variables. If I run it for ec2 (where we _do_ know the IP addresses), I get:

```
./ct --platform=ec2 --pretty < example.clc
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {
    "units": [
      {
        "name": "etcd-member.service",
        "enable": true,
        "dropins": [
          {
            "name": "20-clct-etcd-member.conf",
            "contents": "[Unit]\nRequires=coreos-metadata.service\nAfter=coreos-metadata.service\n\n[Service]\nEnvironmentFile=/run/metadata/coreos\nExecStart=\nExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS \\\n  --listen-peer-urls=\"http://${COREOS_EC2_IPV4_LOCAL}:2380\" \\\n  --listen-client-urls=\"http://0.0.0.0:2379\" \\\n  --initial-advertise-peer-urls=\"http://${COREOS_EC2_IPV4_LOCAL}:2380\" \\\n  --advertise-client-urls=\"http://${COREOS_EC2_IPV4_LOCAL}:2379\" \\\n  --discovery=\"https://discovery.etcd.io/\u003ctoken\u003e\""
          }
        ]
      }
    ]
  },
  "networkd": {},
  "passwd": {}
}
```

If you look closely, you'll see it's using EC2-specific variables (e.g. `COREOS_EC2_IPV4_LOCAL`).
