### ISSUE TITLE
Sample Cluster Configurations Cannot Be Converted To Ignition Via Transpiler

### ISSUE THREAD

**Issue by kurron** [coreos/bugs#1918]
# Issue Report #

## Bug ##
The cluster examples on the [Cluster Architectures](https://coreos.com/os/docs/latest/cluster-architectures.html)  all use cloud-config to describe how to set things up.  As you know, Ignition is replacing cloud-config.  When I tried to use the transpiler to convert the cloud-config examples to Ignition, it blows up.  I would like to see the sample configurations either be in Ignition or in a cloud-config format that can be successfully run through the transpiler.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

```
ct --version
ct v0.2.2
```
### Expected Behavior ###
The sample configurations can be converted by the transpiler.

### Actual Behavior ###

```
ct -in-file sample.yml -pretty -strict

warning at line 2, column 0
Config has unrecognized key: coreos
Failed to parse config
```
### Reproduction Steps ###

  1. copy the sample YML from the web page into `sample.yml`
  2. have the transpiler convert the yaml, `ct -in-file sample.yml -pretty -strict`

### Other Information ###

`sample.yml`
```
#cloud-config

coreos:
  etcd2:
    name: etcdserver
    initial-cluster: etcdserver=http://10.0.0.101:2380
    initial-advertise-peer-urls: http://10.0.0.101:2380
    advertise-client-urls: http://10.0.0.101:2379
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://0.0.0.0:2380
  units:
    - name: etcd2.service
      command: start
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=eth0

        [Network]
        DNS=1.2.3.4
        Address=10.0.0.101/24
        Gateway=10.0.0.1
```
### Other Information ###
Just wanted to note that having the examples in the documentation work with Ignition will make it easier for folks to adopt Container Linux and Tectonic.

**Comment by kostasns** [comment]
You don't need `#cloud-config` and `coreos:` in YAML file which you will be passing to ct. I found [this doc](https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md) very useful to get started with ct.

**Comment by kurron** [comment]
I guess my problem is that I don't know either format well enough to translate from cloud-config to Ignition.  I just want to set up a small CoreOS cluster so I can begin experiments.  I'm close, I just need a little help from folks who understand the system better than I.  I tried just pulling out the elements you suggested but it still blows up, which makes sense given the specification.

```
etcd2:
    name: etcdserver
    initial-cluster: etcdserver=http://10.0.0.101:2380
    initial-advertise-peer-urls: http://10.0.0.101:2380
    advertise-client-urls: http://10.0.0.101:2379
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://0.0.0.0:2380
units:
    - name: etcd2.service
      command: start
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=eth0

        [Network]
        DNS=1.2.3.4
        Address=10.0.0.101/24
        Gateway=10.0.0.1
```

```
ct -in-file hacked.yml -pretty -strict
warning: Config has unrecognized key: etcd2
warning at line 9, column 0
Config has unrecognized key: units
Failed to parse config
```
