### ISSUE TITLE
CoreOS Enterprise Registry Deployed in Swarm: Setup can't continue: Redis validation field is blocking

### ISSUE THREAD

**Issue by marcellodesales** [coreos/bugs#1944]
## Bug ##

While trying to deploy the CoreOS Enterprise Registry to a Docker Swarm, I had to use a workaround to setup the instance. The form field for the redis server is validating as *incorrect* the host name with `_` characters.

### Environment ###

* Docker Swarm with Docker Engine 17.03
* Amazon EC2 with ELB

### Expected Behavior ###

The UI should allow me to use the name of the host as `registry_redis`.

### Actual Behavior ###

* Validation of the form field of Redis host fails the setup.

<img width="933" alt="screen shot 2017-04-28 at 5 39 53 pm" src="https://cloud.githubusercontent.com/assets/131457/25551666/11b3f48a-2c3d-11e7-9b43-a826dcd5d7e9.png">

### Reproduction Steps ###

* Deploying using `docker stack -c quay-stack.yml --with-registry-auth registry` command.
 * Requires registry auth. It assumes you have a file under `/home/ec2-user/.docker/config.json`
 * As a result, the name of the container/host in swarm is `registry_redis`

```yml
version: '3'
services:
  registry:
    image: quay.io/coreos/quay:v2.3.2
    privileged: true
    restart: always
    ports:
      - "80:80"
    volumes:
      coreos-registry:
    deploy:
      replicas: 1
      labels: [APP=REGISTRY]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]

  redis:
    image: quay.io/quay/redis
    ports:
      - "6379:6379"
    labels:
      net.company.docker.hub.type: "Data Structure Store"
      net.company.docker.hub.info: "Docker Registry Redis Server"
    deploy:
      replicas: 1
      labels: [APP=REDIS]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - coreos-registry:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "coreos_registry"
    labels:
      net.company.docker.hub.type: "Database"
      net.company.docker.hub.info: "Docker Registry MySQL Server"
    deploy:
      replicas: 1
      labels: [APP=MYSQL]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]

volumes:
  coreos-registry:
```

### Workaround ###

* `docker service rm registry_redis`
* docker service create --name redis --publish=6379:6379/tcp --network registry_default quay.io/quay/redis

* Using the redis host `redis` I could setup the registry.

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
