### ISSUE TITLE
container-linux-config-transpiler examples.md documentation

### ISSUE THREAD

**Issue by jbkc85** [coreos/bugs#1951]
# Issue Report #

### URL ###

https://coreos.com/os/docs/latest/clc-examples.html

https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/examples.md

### Documentation in Question ###

In the 'Users and Groups' section, would the second example for users be incorrect due to the missing 'create:' object?

---
```
passwd:
  users:
    - name: user1
      password_hash: password1
      ssh_authorized_keys:
        - key1
        - key2
    - name: user2
      ssh_authorized_keys:
        - key3
```

This example will create two users, user1 and user2. The first user has a password set and two ssh public keys authorized to log in as the user. The second user doesn't have a password set (so log in via password will be disabled), but have one ssh key.

---

In other documentation, it mentions that if the ``create:`` object is missing users won't actually be created...the above will simply append configurations onto existing users.

### Suggested Fix ###

If this is in fact the case:

Either adjust the text below the example to note that it only affects pre-existing users OR add the needed ``create:`` object values to the example.
