### ISSUE TITLE
password_hash not working

### ISSUE THREAD

**Issue by davenport** [coreos/bugs#1954]
# Issue Report #

### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"

### Environment ###

VMWare/vSphere 6U2

### Expected Behavior ###

supply password_hash and be able to ssh as "core" user via a passwod

for demonstration I'm using the hash created by:

perl -e 'print crypt("password","\$6\$SALT\$") . "\n"'
$6$SALT$3MUMz4cNIRjQ/Knnc3gXjJLV1vdwFs2nLvh//nGtEh/.li04NodZJSfnc4jeCVHd7kKHGnq5MsenN.tO6Z.Cj/

### Actual Behavior ###

when I ssh as the "core" user using "password" it fails

### Reproduction Steps ###

the relevant ignition YAML...

```
passwd:
  users:
    - name: core
      password_hash: $6$SALT$3MUMz4cNIRjQ/Knnc3gXjJLV1vdwFs2nLvh//nGtEh/.li04NodZJSfnc4jeCVHd7kKHGnq5MsenN.tO6Z.Cj/
      ssh_authorized_keys:
        - ssh-rsa ...
```
### Other Information ###

NOTE - the ssh-rsa key does work

What am I missing?

Thank you,

Doug
