### ISSUE TITLE
/etc/timezone and timezone value are not honored in cloud-config

### ISSUE THREAD

**Issue by FireDrunk** [coreos/bugs#1957]
# Issue Report #
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
CoreOS OVA on ESXi 6.0

### Expected Behavior ###
Either honor the timezone: value from cloud-init, or use the timezone provided in /etc/timezone.
(Honoring /etc/timezone might be a bug that should be filed upstream with the systmed-timesyncd boys)

### Actual Behavior ###
Timezone will not be changed until you use **timedatectl set-timezone** or **ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime** to a valid timezone manually.

### Reproduction Steps ###

  1. Set the timezone: value in cloud-init **or** set the /etc/timezone with the write_files section

**Comment by dm0-** [comment]
Where did you see a `timezone:` setting for cloudinit?  I don't believe that is valid.

My own config uses the following (based on [the documented example](https://coreos.com/os/docs/latest/cloud-config-examples.html#time)) plus a dependency on e.g. `zone-set@America-Los_Angeles.service` which has no problems:

```yaml
coreos:
  units:
    - name: "zone-set@.service"
      content: |
        [Unit]
        Description=Set the time zone
        
        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone %I
        RemainAfterExit=yes
        Type=oneshot
```

**Comment by FireDrunk** [comment]
A simple google search gave me this example file:
https://github.com/number5/cloud-init/blob/master/doc/examples/cloud-config.txt

I was looking at the following documentation:
https://coreos.com/os/docs/latest/configuring-date-and-timezone.html

On the page they use:
```
# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

storage:
  files:
    - path: /etc/timezone
      filesystem: root
      mode: 0644
      contents:
        inline: America/New_York
```

If i convert this to cloud-init with the write_files, the /etc/timezone file is not used by systemd-timesyncd.

Perhaps this is just a case of outdated documentation. Ill try your solution.
