### ISSUE TITLE
CT configs should support base64 encoded file contents

### ISSUE THREAD

**Issue by colhom** [coreos/bugs#1969]
### Environment ###
tectonic v1.6.2-1 baremetal
matchbox v0.6.0

### Desired Feature ###
Support base64-encoded file contents

### Other Information ###
It's very difficult/error prone to template string literals into yaml. For example, a non-properly indented PEM file will cause YAML templating errors.

Related #1067 

\cc @crawford

**Comment by crawford** [comment]
It's possible to use multi-line escaped strings already (this is part of the YAML spec). Something like this should work (Ignore GitHub's error rendering. It's wrong.):

```yaml
storage:
  files:
    - path: /foo/bar
      filesystem: root
      contents:
        inline: "this\nis\na\nreally\nlong\nstring."
```

Instead of the base64 conversion, you'll just want to escape the newlines.
