### ISSUE TITLE
Behavior of coreos-cloudinit does not match documentation

### ISSUE THREAD

**Issue by larsks** [coreos/bugs#199]
According to https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/, coreos-cloudinit supports the following syntax:

```
coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="10.0.1.0/24"'
```

But attempting to use this example results in the error:

```
line 6: warning: unrecognized key "drop_ins"
```
