### ISSUE TITLE
CT should emit the create object when non-core users are referenced

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#2003]
# Issue Report #

## Bug ##

Straight out of the [documentation](https://github.com/coreos/container-linux-config-transpiler/blob/d2b5fed204802a87e7b532d42b3bae3f15ce97ae/doc/examples.md):

```yaml
# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

passwd:
  users:
    - name: user1
      password_hash: "$6$43y3tkl..."
      ssh_authorized_keys:
        - key1
        - key2
    - name: user2
      ssh_authorized_keys:
        - key3
```

CT generates the following config:

```json
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {},
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "user1",
        "passwordHash": "$6$43y3tkl...",
        "sshAuthorizedKeys": [
          "key1",
          "key2"
        ]
      },
      {
        "name": "user2",
        "sshAuthorizedKeys": [
          "key3"
        ]
      }
    ]
  }
}
```

This causes Ignition to fail since neither of these users exists. CT should add the empty create object in this case to instruct Ignition to create them. This won't be an issue in the future since we deprecated the create object, but this will be needed in the meantime.
