### ISSUE TITLE
Creation of tun interface in cloud-config causes DNS to be ignored for other interface

### ISSUE THREAD

**Issue by ZackAdams** [coreos/bugs#201]
When I create a CoreOS droplet in Digital Ocean with user-data below the DNS appears to be ignored for the pre-configured eth0 interface and nothing is written to /etc/resolv.conf. However if I add a DNS line in 00-tun0.network and restart systemd-networkd it is picked up and added to resolv.conf.
```
#cloud-config

coreos:
  etcd:
    addr: 10.10.0.1:4001
    peer-addr: 10.10.0.1:7001
  fleet:
    public-ip: 10.10.0.1
    metadata: role=service
  units:
    - name: 00-tun0.netdev
      runtime: true
      content: |
        [NetDev]
        Name=tun0
        Kind=tun
    - name: 00-tun0.network
      runtime: true
      content: |
        [Match]
        Name=tun0
        [Address]
        Address=10.10.0.1/24
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
```
