### ISSUE TITLE
ct sets incorrect partition start/size on 4K native disks

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2111]
# Issue Report #

### ct Version ###

```
$ ct -version
ct v0.4.2
```

### Expected Behavior ###

Specifying a partition offset X GiB into the disk, or a size of Y GiB, produces a partition table with exactly those values.

### Actual Behavior ###

On disks with 4 KiB logical sectors, the offset and size are 8 times larger than specified.

### Reproduction Steps ###

  1. Transpile this CLC:

```yaml
storage:
  disks: 
    - device: /dev/vda
      partitions:
        - size: 1GiB
```

  2. Observe that partition 0 is 2097152 sectors, which is 8 GiB on a 4Kn disk.

cc @dgonyeo
