### ISSUE TITLE
XenServer is unable to retrieve CoreOS VM IP address(es) after 1409.2.0 update

### ISSUE THREAD

**Issue by DevKyleS** [coreos/bugs#2123]
# Issue Report #

## Bug ##
Looks like the new Linux version introduced with CoreOS v1409.2.0 and continues to not function as expected for every version up through v1465.60. This looks similar to bug #1563.

### Container Linux Version ###
```
core@coreos140920 ~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.2.0
VERSION_ID=1409.2.0
BUILD_ID=2017-06-19-2321
PRETTY_NAME="Container Linux by CoreOS 1409.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

XenCenter v7.2 (build 7.2.0.5022) 64-bit
XenServer 7.2 64-bit
XenServer Container Management Supplemental Pack (May 25, 2017) for XenServer 7.2 - Container Management (version 1.0)
Applied Updates: XS72E001, XS72E002, XS72E003, XS72E004, XS72E005
```
[root@idev-xenserver ~]# cat /proc/version && uname -a
Linux version 4.4.0+10 (mockbuild@5893213cc32e) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Thu Aug 10 20:29:14 UTC 2017
Linux idev-xenserver 4.4.0+10 #1 SMP Thu Aug 10 20:29:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected Behavior ###
- CoreOS boots
- Operating System: Container Linux by CoreOS 1409.2.0 (Ladybug)
- Virtualization mode: Hardware-assisted Virtualization (HVM)
- Virtualization state: Optimized (version 7.1 installed)
- XenCenter shows IP address(es) in Networking tab for VM
- XenCenter is able to manage Docker containers and viewable through XenCenter

### Actual Behavior ###
- CoreOS boots
- Operating System: Unknown
- Virtualization mode: Hardware-assisted Virtualization (HVM)
- Virtualization state: Optimized (version 6.2 installed)
- XenCenter Networking tab says "Unknown" for IP Addresses even though the console says it has both IPv4 address(es) and IPv6 address(es)

### Reproduction Steps ###

  1. Create New VM with CoreOS template using iso
  2. Configure Cloud-Config drive with below **default** template
```
#cloud-config

hostname: %VMNAMETOHOSTNAME%
ssh_authorized_keys:
  # The following entry will automatically be replaced with a public key
  # generated by container management plugin. The key-entry must exist,
  # in order to enable container management for this VM.
  - ssh-rsa %CONTAINERRSAPUB%
coreos:
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

    # Hypervisor Linux Guest Agent
    - name: xe-linux-distribution.service
      command: start
      content: |
        [Unit]
        Description=Hypervisor Linux Guest Agent
        After=docker.service

        [Service]
        ExecStartPre=/media/configdrive/agent/xe-linux-distribution /var/cache/xe-linux-distribution
        ExecStart=/media/configdrive/agent/xe-daemon
  etcd:
    name: %VMNAMETOHOSTNAME%
    # generate a new token for each unique cluster at https://discovery.etcd.io/new
    # discovery: https://discovery.etcd.io/<token>
write_files:
  # Enable ARP notifications for smooth network recovery after migrations
  - path: /etc/sysctl.d/10-enable-arp-notify.conf
    permissions: 0644
    owner: root
    content: |
      net.ipv4.conf.all.arp_notify = 1


# Template loaded from /usr/lib/python2.7/site-packages/xscontainer/data/cloud-config.template
```
3. Enable Container management through XenCenter
4. Boot VM
5. Open XenCenter, navigate to VM's General, Networking, and Console tabs

### Other Information ###
- The console screen for the non-working v1409.2.0 has the following error.
```
Container Linux by CoreOS stable (1409.2.0)
Update Strategy: No Reboots
Failed Units: 1
  user-configdrive.service
core@coreos140920 ~ $
```
