### ISSUE TITLE
Double-escaping locksmithd strings

### ISSUE THREAD

**Issue by eshicks4** [coreos/bugs#2147]
# Issue Report #

### Container Linux Version ###

```
computer:container-linux-config-transpiler root# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

### Expected Behavior ###

```
locksmith:
  reboot_strategy: etcd-lock
  etcd_endpoints: https://internal-etcd-balancer.us-east-2.elb.amazonaws.com:2379
  etcd_cafile: /etc/ssl/certs/CA.pem
  etcd_certfile: /etc/ssl/certs/etcd-cert.pem
  etcd_keyfile: /etc/ssl/certs/etcd-key.pem
```

Should produce correct JSON for /etc/coreos/update.conf

### Actual Behavior ###
```
{
  "filesystem" : "root",
  "contents" : {
    "verification" : {},
    "source" : "data:,%0AREBOOT_STRATEGY%3D%22etcd-lock%22%0ALOCKSMITHD_ENDPOINT%3D%22%5C%22https%3A%2F%2Finternal-etcd-balancer.us-east-2.elb.amazonaws.com%3A2379%5C%22%22%0ALOCKSMITHD_ETCD_CAFILE%3D%22%5C%22%2Fetc%2Fssl%2Fcerts%2FCA.pem%5C%22%22%0ALOCKSMITHD_ETCD_CERTFILE%3D%22%5C%22%2Fetc%2Fssl%2Fcerts%2Fetcd-cert.pem%5C%22%22%0ALOCKSMITHD_ETCD_KEYFILE%3D%22%5C%22%2Fetc%2Fssl%2Fcerts%2Fetcd-key.pem%5C%22%22"
  },
  "user" : {},
  "mode" : 420,
  "group" : {},
  "path" : "/etc/coreos/update.conf"
}
```

Which when decoded produces:

```
REBOOT_STRATEGY="etcd-lock"
LOCKSMITHD_ENDPOINT="\"https://internal-etcd-balancer.us-east-2.elb.amazonaws.com:2379\""
LOCKSMITHD_ETCD_CAFILE="\"/etc/ssl/certs/CA.pem\""
LOCKSMITHD_ETCD_CERTFILE="\"/etc/ssl/certs/etcd-cert.pem\""
LOCKSMITHD_ETCD_KEYFILE="\"/etc/ssl/certs/etcd-key.pem\""
```

### Reproduction Steps ###

See above

### Other Information ###

My guess would be that it has to do with the fact that it reads from a special "locksmithd:" section but implements by creating a file in the resulting "storage:" section.  It might be getting escaped both at input and output.
