### ISSUE TITLE
Error retrieving list of active machines: googleapi: Error 503

### ISSUE THREAD

**Issue by idi-ot** [coreos/bugs#2185]
### Container Linux Version ###

```sh
core@core-03 ~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1548.0.0
VERSION_ID=1548.0.0
BUILD_ID=2017-09-27-0012
PRETTY_NAME="Container Linux by CoreOS 1548.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
vagrant and digitalocean, same error on both.

### Expected Behavior ###
```sh
core@core-03 ~ $ fleetctl list-machines
# lists machines
```

### Actual Behavior ###
```sh
core@core-03 ~ $ fleetctl list-machines
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
```
### Reproduction Steps ###

  1. Get token `curl "https://discovery.etcd.io/new?size=3"`
  2. Use token in `cl.conf`
```yaml
etcd:
  name: "{HOSTNAME}"
  listen_peer_urls: "http://{PRIVATE_IPV4}:2380"
  listen_client_urls: "http://0.0.0.0:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  advertise_client_urls: "http://{PRIVATE_IPV4}:2379"
  discovery: "https://discovery.etcd.io/<token>"

systemd:
  units:
    - name: docker-tcp.socket
      enabled: true
      contents: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
    - name: fleet.service
      enabled: true
    - name: etcd2.service
      enabled: true
    - name: flanneld.service
      dropins:
        - name: 50-network-config.conf
          contents: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /flannel/network/config '{ "Network": "10.1.0.0/16" }'

flannel:
  etcd_prefix: "/flannel/network"
```
3. `ct --platform=digitalocean < cl.conf > config.ign` or `ct --platform=vagrant-virtualbox < cl.conf > config.ign`
4. create three droplets with digital ocean or `vagrant up`
