### ISSUE TITLE
SSH key from metadata missing in OpenStack environment

### ISSUE THREAD

**Issue by Sebmaster** [coreos/bugs#2247]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

Tried with latest alpha as well.

### Environment ###

OpenStack

### Expected Behavior ###

I should be able to log in with my cloud-provided SSH key and the `core` user.

### Actual Behavior ###

The `core` user doesn't have the SSH key authorized.

### Reproduction Steps ###

1. Use any ignition config, I used the following compiled with `ct --in-file=coreos-init.yml --platform=openstack-metadata` for testing:

```yml
passwd:
  users:
    - name: user
      groups:
        - sudo
        - docker
      ssh_authorized_keys:
        - "ssh-rsa AAAAB ..."
```

2. Try `ssh core@host`. Public Key auth fails.
3. Try `ssh user@host`, works fine.

### Other Information ###

I got it to work by adding 

```yml
systemd:
  units:
    - name: "coreos-metadata-sshkeys@.service"
      enabled: true
```

to the yaml since I looked at the source code in ignition. Seems like this is not set for OpenStack, but is for some other providers.
