### ISSUE TITLE
directory/file modes not applying

### ISSUE THREAD

**Issue by port22** [coreos/bugs#2255]
### Container Linux Version ###
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.1.0
VERSION_ID=1576.1.0
BUILD_ID=2017-10-26-0503
PRETTY_NAME="Container Linux by CoreOS 1576.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
What hardware/cloud provider/hypervisor is being used to run Container Linux?

> vmware esxi

### Expected Behavior ###

> file / direcotry modes are being applyed as stated in container linux config.

### Actual Behavior ###

> /root/.ssh has 770
> /root/.ssh/id_rsa has 620

### Reproduction Steps ###

```
storage:
  directories:  
    - filesystem: root
      path: /root/.ssh
      mode: 700
      user:
        id: 0
      group:
        id: 0
  files:
     - filesystem: root
      path: /root/.ssh/id_rsa
      mode: 400
```
