### ISSUE TITLE
coreos.autologin set in ContainerLinuxConfig

### ISSUE THREAD

**Issue by port22** [coreos/bugs#2257]
I want to enable coreos.autologin by default (so I can attach to the vmware esx console on emergency)

```
storage:
  files:
    - filesystem: root
      path: /usr/share/oem/grub.cfg
      contents: 
        inline: set linux_append="coreos.autologin"
```

At the stage where  coreos want's to write the content into the grub.cfg, the /system mount is read-only.

How do I set autologin per container linux config/ignition?

**Comment by dghubble** [comment]
I recall the filesystem is `oem` to write that file, not `root`.

**Comment by ajeddeloh** [comment]
@dghubble I'm not sure if Ignition can write there actually. The baseconfig only specifies `root` and I don't think any providers add oem. You _might_ be able to do it by adding a `storage.filesystems` entry for the OEM partition, but I'm not sure how well that would work. It certainly would need a reboot at the very least.

A better option would be to see if there's a VMware specific way to add kernel command line options.

**Comment by dghubble** [comment]
I believe it was part of an Ignition config being used for the install to disk and reboot stage, that added the file and ran `coreos-install`. If it is possible, the install likely tramples the grub.cfg with a default though. I'll try to dig up the earlier discussion.

**Comment by dghubble** [comment]
[Discussion](https://github.com/poseidon/typhoon/issues/30#issuecomment-334492605) and an [example](https://gist.github.com/bzub/edfd2a69d47de1fa3375d9e855ccc272) from bzub.

**Comment by ajeddeloh** [comment]
Gotcha. It should still need a reboot, since those arguments will only be parsed at the start of boot, yes?

**Comment by bgilbert** [comment]
A reboot will still be needed, yes.  Because Ignition currently can't append to files (#1997) this unavoidably overwrites the existing contents of `grub.cfg`, which is not recommended.  A better approach might be to write a `ConditionFirstBoot` systemd service which appends to `grub.cfg` (and possibly also reboots the system).

**Comment by crawford** [comment]
Alternatively, you should be able to do something like:

```yaml
systemd:
  units:
    - name: serial-getty@.service
      dropins:
        - name: 10-autologin.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=-/sbin/agetty --autologin core --keep-baud %I 115200,38400,9600 $TERM
    - name: getty@.service
      dropins:
        - name: 10-autologin.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=-/sbin/agetty --autologin core --noclear %I $TERM
    - name: emergency.service
      dropins:
        - name: 10-autologin.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=-/bin/sh -c "/usr/bin/login -f root; /usr/bin/systemctl --job-mode=fail --no-block default"
```

This won't require the reboot since it isn't modifying the kernel command line.

This is pulled from the [autologin generator](https://github.com/coreos/init/blob/00977cf5432bb014aa6e03ffef316df9237ad745/systemd/system-generators/coreos-autologin-generator).
