### ISSUE TITLE
Ignition Create Files from Remote Contents stuck forever at writing file step

### ISSUE THREAD

**Issue by davide-talesco** [coreos/bugs#2272]
# Issue Report #
## Bug ##
Ignition gets stuck at fetching the file from the url

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

Vsphere 

### Expected Behavior ###
Ignition completes the download of the remote file and complete the boot procedure

### Actual Behavior ###
Ignition gets stuck at fetching the file from the url and boot does not proceed.
The console show the following message forever:
[started] writing file "/opt/bin/kubectl"
[] A start job is running for ignition (files)

### Reproduction Steps ###
1- Create the following linux configuration config file
```
storage:
  files:
    - filesystem: root
      path: /opt/bin/kubectl
      contents:
        remote:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.8.3/bin/linux/386/kubectl
      mode: 493
```
2- Process it (with no errors) with ct (v0.5.0) to get the following ignition file:
```
{
  "ignition": {
    "config": {},
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "group": {},
        "path": "/opt/bin/kubectl",
        "user": {},
        "contents": {
          "source": "https://storage.googleapis.com/kubernetes-release/release/v1.8.3/bin/linux/386/kubectl",
          "verification": {}
        },
        "mode": 493
      }
    ]
  },
  "systemd": {}
}
```
3- Deploy a coreos machine and attach above ignition configuration
4- The boot stay stuck at writing the file forever

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Vsphere
