### ISSUE TITLE
Do not suggest Zsh in config example

### ISSUE THREAD

**Issue by ruuda** [coreos/bugs#2274]
# Issue Report #

This is an issue in the documentation, specifically at the following url:

https://coreos.com/os/docs/latest/clc-examples.html

“Latest” at the moment is 1590.0.0.

The page contains the following example:

```yaml
passwd:
  users:
    - name: user1
      password_hash: "$6$43y3tkl..."
      ssh_authorized_keys:
        - key1
      home_dir: /home/user1
      no_create_home: true
      groups:
        - wheel
        - plugdev
      shell: /bin/zsh
```
This suggests that it is possible to set the shell to Zsh, but `/bin/zsh` does not exist, [and there is no intention to add it](https://github.com/coreos/bugs/issues/372). **If you actually use this configuration, it will be impossible to log in.** At least, I was unable to log in either on a tty or via ssh on stable 1520.8.0 in Qemu, until I removed the `shell` line from the config.

I suggest changing `/bin/zsh` to `/bin/bash` in the example.
