### ISSUE TITLE
 container-linux-config-transpiler: storage.links entry is not converted

### ISSUE THREAD

**Issue by gitsparky** [coreos/bugs#2352]
# Issue Report #

## Bug ##

A "links" entry in container config file is missing from the generated ignition config file.

In browsing the source code on master as of commit cf05bf5 it seems like there should be a file `config/types/links.go` (which is included by `types/storage.go`) but this file does not exist.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"                             
ID=coreos                                                    
VERSION=1675.0.1                                             
VERSION_ID=1675.0.1                                          
BUILD_ID=2018-02-02-0056                                     
PRETTY_NAME="Container Linux by CoreOS 1675.0.1 (Rhyolite)"  
ANSI_COLOR="38;5;75"                                         
HOME_URL="https://coreos.com/"                               
BUG_REPORT_URL="https://issues.coreos.com"                   
COREOS_BOARD="amd64-usr"                                     
```

Probably more relevant is the version of the transpiler, I used binary from the releases page: `ct-v0.6.1-x86_64-pc-windows-gnu.exe`

### Environment ###

Vagrant + Virtualbox on Windows

### Expected Behavior ###

A `"links"` section should be added to the generated `config.ign`

### Actual Behavior ###

No `"links"` entry appears under `"storage"` key.

### Reproduction Steps ###

  1. Create a `cl.conf` with a "links" section, for example:
```
storage:
  directories:
    - filesystem: "root"
      path: "/opt/bin"
      mode: 493 # aka 0755
  links:
    - filesystem: "root"
      path: "/etc/localtime"
      target: "/usr/share/zoneinfo/US/Eastern"
      hard: false
  files:
    - filesystem: "root"
      path: "/home/core/.ssh/id_rsa"
      contents:
        local: ".ssh/id_rsa"
      mode: 384 # aka 0600
```

  2. Run this through the transpiler:
```bash
$ ct-v0.6.1-x86_64-pc-windows-gnu.exe  --platform=vagrant-virtualbox --files-dir=./filesync --pretty --strict --in-file cl.conf --out-file config.ign
```

 3. Scratch your head why the `config.ign` doesn't have "links" entry
