### ISSUE TITLE
docker.service's DOCKER_OPTS is ignored when flanneld.service is active

### ISSUE THREAD

**Issue by tatsuya6502** [coreos/bugs#244]
Hello.

I'm trying CoreOS 557.0.0 from alpha channel.

```
core@core-01 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=557.0.0
VERSION_ID=557.0.0
```

I'm running **flanneld.service**. And also I'd like to override `DOCKER_OPTS` in **docker.service** from cloud config. So my cloud config looks like this.

```
  units:
    - name: etcd.service
      command: start
    - name: flanneld.service
      # IMPORTANT: flanneld.service needs to be listed before any services that
      # run Docker containers. This includes fleet.service as fleet daemon will
      # start unit that may run Docker containers.
      # https://coreos.com/docs/cluster-management/setup/flannel-config/
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      drop-ins:
        - name: 50-dns-search.conf
          content: |
            [Service]
            Environment='DOCKER_OPTS=--dns-search=localdomain --insecure-registry="0.0.0.0/0"'
```

However, my `DOCKER_OPTS` doesn't appear in systemd status (the last line for PID 2456).

```
core@core-01 ~ $ cat /etc/systemd/system/docker.service.d/50-dns-search.conf
[Service]
Environment='DOCKER_OPTS=--dns-search=localdomain --insecure-registry="0.0.0.0/0"'

core@core-01 ~ $ sudo systemctl start docker.service
core@core-01 ~ $ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib64/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─50-dns-search.conf
   Active: active (running) since Fri 2015-01-16 10:19:55 UTC; 6s ago
     Docs: http://docs.docker.com
 Main PID: 2456 (docker)
   CGroup: /system.slice/docker.service
           └─2456 docker --daemon --host=fd:// --ip-masq=false --bip=10.1.13.1/24 --mtu=1472
```

I think my `DOCKER_OPTS` is overwritten by another `DOCKER_OPTS` in `/run/docker_opts.env`. This file is created by flanneld.service.

Here is a relevant section from the doc.

https://coreos.com/docs/cluster-management/setup/flannel-config/

> - 5. `ExecStartPost` in `flanneld.service` converts information in
>   `/run/flannel/subnet.env` into Docker daemon command line args (such
>   as `--bip` and `--mtu`), storing them in `/run/docker_opts.env`
> - ...
> - 7. `docker.service` sources in `/run/docker_opts.env` (which
>   contains `DOCKER_OPTS`) and starts the Docker daemon with
>   `$DOCKER_OPTS`

I think we cloud rename this `DOCKER_OPTS` (from flanneld.service) to something else like `DOCKER_NET_OPTS`, so that we can have the both options in effect?

Thanks,
