### ISSUE TITLE
CoreOS 1855.4.0 AWS EBS 

### ISSUE THREAD

**Issue by pctj101** [coreos/bugs#2511]
# Issue Report #

## Bug ##
Ignition crashes system if storage.filesystem is specified

CT Input
```
storage:
  filesystems:
    - name: data
      mount:
        device: /dev/sdb
        format: ext4
        wipe_filesystem: true
        label: DATA
```

Convert to userdata
ct < test.ct 
```
{"ignition":{"config":{},"security":{"tls":{}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{"filesystems":[{"mount":{"device":"/dev/sdb","format":"ext4","label":"DATA","wipeFilesystem":true},"name":"data"}]},"systemd":{}}
```

### Container Linux Version ###
CoreOS-stable-1855.4.0-hvm (ami-086eb64b7f4485a72)
ct v0.9.0

### Environment ###
AWS 

### Expected Behavior ###
At minimum format my block device

### Actual Behavior ###
System does not boot
Can't login, so can't get logs
Screenshot
https://www.evernote.com/l/AE__MLODCjJN_p8vv9G_LkqC2nBnb6BbAqI

### Reproduction Steps ###

  1. Create EC2 instance, attach 80GB EBS to /dev/sdb, add user data, boot and crash

### Other Information ###

Worked before on older CoreOS-stable-1688.5.3-hvm (ami-a2b6a2de)

Manually booting without CT/Ignition allows manual format/mounting of /dev/sdb (mounting by label is also no problem)
