### ISSUE TITLE
CT has no documentation on how to use

### ISSUE THREAD

**Issue by spuder** [coreos/bugs#2595]
I've downloaded CT according to the documentation. 

     brew install coreos-ct

I've created a config file as shown in the documentation

```yaml
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1ycxxxxxxx
```

There is no documentation on how to actually use `ct`. There is no man page, or clear examples of how to use the CLI. 

I'm guessing you pass a yaml file to the cli. When I try, nothing happens. 

```
$ ct foo.yaml # <- this command hangs and never responds
````

Trying to call the CLI directly gives the same result

```
$ ct # <- command hangs, and is waiting for input
```

This shouldn't be this hard. Please provide a clear example of how to configure a container linux machine.
