### ISSUE TITLE
How can I change /etc/passwd and /etc/passwd- file permissions via Ignition

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2618]
# Issue Report #
How can I change /etc/passwd and /etc/passwd- file permissions via Ignition

### Container Linux Version ###
2191.5.0
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###
My Container linux config file has:
```
storage:
  files:
    - path: /etc/passwd
      filesystem: root
      mode: 0644
      user: 
        name: root
      group: 
        name: root
    - path: /etc/passwd-
      filesystem: root
      mode: 0640
      user: 
        name: root
      group: 
        name: root
```
### Expected Behavior ###

File permissions must be set as specified

### Actual Behavior ###
Both /etc/passwd and /etc/passwd- has 644 permission
![image](https://user-images.githubusercontent.com/8611615/66740555-187ca000-ee91-11e9-9fe9-18c91fbe0e5d.png)

### Reproduction Steps ###

  1. ...
  2. ...
