### ISSUE TITLE
How to append multiple ignition configs?

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2654]
If I create Ignition.yaml as
![image](https://user-images.githubusercontent.com/8611615/72780243-5f262700-3c44-11ea-8d86-80c411829f5c.png)
It will append one ignition.

I want to append one more ignition in it.
How can that be done?

**Comment by bgilbert** [comment]
As the [docs](https://coreos.com/os/docs/latest/configuration.html) say, the `append` object is a list.  So you'd do:

```
ignition:
  config:
    append:
      - source: "https://"
      - source: "https://"
```

coreos/bugs is not intended as a channel for obtaining extended support.  Please send support questions to the [coreos-user](https://groups.google.com/forum/#!forum/coreos-user) mailing list instead.  Thanks!
