### ISSUE TITLE
Passing flags to Docker daemon

### ISSUE THREAD

**Issue by errordeveloper** [coreos/bugs#268]
I can see that coreos/coreos-overlay@504faa1495e599e427f7d1e041c945436202ab34 has changed `/run/docker_opts.env` to `/run/flannel_docker_opts.env`.

I think there should be a official way of appending the arguments passed to Docker daemon.

**Comment by crawford** [comment]
You can use a drop-in on docker.service to set $DOCKER_OPTS.

```
#cloud-config

coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="10.0.1.0/24"'
```
