### ISSUE TITLE
Specifying group "systemd-journal" in cloud-init doesn't work

### ISSUE THREAD

**Issue by pwaller** [coreos/bugs#312]
I've got a system service and I want it to be able to read the systemd logs. To do that, it needs to be in the `systemd-journal` group. However, specifying it under "groups" has no effect. Groups works, but not for this system group.

Is it possible to make this work?

``` yaml
users:
  # system services
  - name: log
    groups: [systemd-journal]
```
