### ISSUE TITLE
disk-install cloud-config network setup + network dependency not working

### ISSUE THREAD

**Issue by JeanMertz** [coreos/bugs#326]
This is somewhat related to #11, in which @crawford explained how to setup a network stack using `cloud-config` when doing a disk-install.

We're installing CoreOS on bare-metal. We provide a `cloud-config.yml` file, but the file both sets up the networking stack, and also has tasks that depend on a working network (like `coreos.etcd.addr`, `coreos.etcd.discovery`, and `users. coreos-ssh-import-github-users`).

We noticed the machine not booting as expected, and investigating showed that the config file - while parsed partially - failed eventually, due to network issues.

Now, I did read somewhere (a while ago) that `cloud-init` shouldn't be confused with a full-stack provisioning tool like `Ansible`, but something as basic as starting etcd should probably work.

Is there some way we can make sure the network stack gets setup first, after which etcd is configured, without using something like Ansible for this? 

For reference, here is the cloud-config file we tried to use:

```bash
$ coreos-install -d /dev/sda -C stable -c /home/core/cloud-config.yaml
```

```yml
#cloud-config

hostname: docker01

coreos:  
  etcd:
    name: docker01
    discovery: https://discovery.etcd.io/zzz
    addr: 172.16.16.21:4001
    peer-addr: 172.16.16.21:7001

  fleet:
    public-ip: 95.211.xxx.yy

  update:
    reboot-strategy: "off"
    group: stable

  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: 10-internal.network
      content: |
        [Match]
        Name=eno3
        [Network]
        Address=172.16.16.21
        DNS=8.8.8.8
        DNS=8.8.4.4

    - name: 20-public.network
      content: |
        [Match]
        Name=eno1
        
        [Network]
        Address=95.211.xxx.yy/27
        Gateway=95.211.xxx.yy
        DNS=8.8.8.8
        DNS=8.8.4.4
        
        [Address]
        Address=95.211.xxx.yy/27
        Broadcast=95.211.xxx.yy

    - name: 30-dhcp.network
      content: |
        [Match]
        Name=eno*
        
        [Network]
        DHCP=yes

users:
  - name: blendle
    passwd: $x$yyyyy.
    ssh-authorized-keys:
      - ssh-rsa xxx
    coreos-ssh-import-github: JeanMertz
    groups:
      - sudo
      - docker
```

**Comment by ArKam** [comment]
Did you solved this issue ?
I'm facing the same problem on my own bare-metal server installation too.

We apparently have to reboot once the install completed or restart/reload the .network netword's units.

**Comment by crawford** [comment]
*sigh* This class of bugs is actually the motivating factor behind [Ignition](https://github.com/coreos/ignition). I don't mean to tease you with this solution, but just raise awareness about its eventual existence. We are getting very close to including this in CoreOS.

As it exists today, using coreos-cloudinit you need to:
1. Write the network config to disk
2. stop networkd
3. take down the interfaces
4. start networkd

With Ignition you'll need to:
1. Write the network config to disk

**Comment by ArKam** [comment]
Ok so, waiting until the release of ignition, how am I suppose to provisions my servers automatically without having to login and create/write a configuration? Using the write_files command?

**Comment by crawford** [comment]
Just use the cloud-config as you normally would. If that includes setting up the network, then you'll need to use the 4-step process I mentioned above. You can do this from a cloud-config, so there shouldn't be any manual steps involved.

**Comment by ArKam** [comment]
Hum, ok cool, How am I suppose to stop and start a unit on a cloud-config? I never saw such a thing, except from a script loaded by the cloud-config.

Is there any command similar to the start directive?

**Comment by crawford** [comment]
https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md#configuration-parameters

**Comment by ArKam** [comment]
Ok, thanks a lot for your time and help @crawford.

One last thing, I'm using CoreOS 681.1.0 with ETCD2 and even if I follow the documentation, it seems that the systemd-netword service is not available as when I execute a sudo systemct (restart/start or stop) systemd-networkd, systemctl complain about the fact that this service is not existing (No such file or directory).

Do I missed something?
For information, if you've got time to take a look at my cloud-init file it would be awesome to let me know if I missed something.

Here it is: https://github.com/ArKam/seed/blob/master/cloud-config-coreos.yml

I plan to write a complete article on how to create a CoreOS Production DEMO platform for information as I really think that the learning curve on CoreOS is a little bit chaotic even it is really simple.
Many steps on your official documentation seems a little bit incoherent or structurally incorrect.

**Comment by crawford** [comment]
> after some investigation, it appears I can't have my nic set by networkd because it automatically select the zz-default.network and 99-default.link parameters, which ask it to use DHCP.

That's why you need to restart network after cloud-init has written the new config. I see you are still missing that step in your cloud-config.

**Comment by ArKam** [comment]
hum, the problem is that the cloud-init do not write my *.network file during the install process, I have to write it myself manually on the host for now.
Additionally, even after having write this file on the host, if I stop and start again the networkd service it will not use my network file.

Is that possible that the install process do not write my network unit because of the missing steps you pointed out?

**Comment by crawford** [comment]
The install process does not write any of those files. They are created on first boot instead. The install script just writes the base image to disk along with your cloud-config.

**Comment by ArKam** [comment]
Hummm ok, I've just understand the underlying process, in that case, why don't coreos do not execute the required directives, I plan to use coreos on our production clusters, but only if it is stable enough and act as it should.

I could maybe help you to debug this situation?

For now I will try your recommendation and just write the config to disk and then restart the systemd-networkd service.

**Comment by crawford** [comment]
This is a deliberate design decision to help ensure that we can use the same OS between bare metal and cloud providers. If we were to depend on offline modifications to the machine by the install script, we would not be able to use the same images for cloud providers (since they do not allow this offline modification). The other thing to keep in mind is that coreos-cloudinit runs on every boot. Even if you did these offline modifications, you would still need to install your cloud-config in the instance.

**Comment by ArKam** [comment]
Ok, I think I had a misunderstanding on how coreos-cloudinit work.

using your explanations, and a new cloud-config file everything seems good to go, my interface now use the expected IP address.

Here is my cloud-config file: https://github.com/ArKam/seed/blob/master/cloud-config-coreos.yml

I will use this repository to write an article/demo about distributed infrastructures/services that people could use to generate POC.

So, many thanks for patience and support, I can check that your recommendation works like a charm without modifying too much of the cloud-config structure.
Let's us informed about ignition by the way as it seems to be really interesting.

**Comment by remoe** [comment]
Hi 

I've tried this with a "bare metal" installation on VBOX with CoreOS Alpha. I've updated the /var/lib/coreos-install/user_data to change set the public interface to DHCP and the internal to static like:

```yml
  units:
    - name: 10-static.network
      runtime: true
      content: |
        [Match]
        Name=enp0s8

        [Network]
        Address=172.18.8.1/24
        DHCP=no
    - name: 20-dhcp.network
      runtime: true
      content: |
        [Match]
        Name=en*

        [Network]
        DHCP=yes
    - name: systemd-networkd
      command: stop
    - name: systemd-networkd
      command: start
```

But after boot I don't see any changes on the network ip.
