### ISSUE TITLE
Unable to boot etcd2 in proxy mode via cloud-config

### ISSUE THREAD

**Issue by bcwaldon** [coreos/bugs#415]
I provided the following cloud-config to my machine:

```
#cloud-config
coreos:
  etcd2:
    proxy: on
  units:
  - name: etcd2.service
    command: start
```

...but etcd2.service fails to start with the following logs:

```
Jul 21 18:57:26 w1 systemd[1]: Starting etcd2...
Jul 21 18:57:26 w1 etcd2[1451]: 2015/07/21 18:57:26 etcd: invalid value "true" for ETCD_PROXY: invalid value
Jul 21 18:57:26 w1 systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
```

Digging in, I see that coreos-cloudinit created the following drop-in:

```
# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_INITIAL_CLUSTER=http://172.17.4.101:2379"
Environment="ETCD_LISTEN_CLIENT_URLS=http://127.0.0.1:2379"
Environment="ETCD_PROXY=true"
```

I believe `ETCD_PROXY=true` env var should actually be `ETCD_PROXY=on`. After making this change manually, etcd2 does successfully start in proxy mode.

```
$ etcd2 -version
etcd Version: 2.0.13
Git SHA: 92e3895
Go Version: go1.4.2
Go OS/Arch: linux/amd64

$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=745.1.0
VERSION_ID=745.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 745.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by crawford** [comment]
OK, it looks like the proxy flag is actually an enum: https://github.com/coreos/etcd/blob/953a59d5543b88f1ed1ea28e9591c84b148ac035/etcdmain/config.go#L129.

**Comment by crawford** [comment]
@bcwaldon use this instead (quotes):

```yaml
#cloud-config
coreos:
  etcd2:
    proxy: "on"
  units:
  - name: etcd2.service
    command: start
```

YAML is such a troll.
