### ISSUE TITLE
Error 503: fleet server unable to communicate with etcd

### ISSUE THREAD

**Issue by YP28** [coreos/bugs#428]
CoreOS 723.3.0 (stable)

I'm trying to set up a testing environment on DigitalOcean, but for some reason I can't get it to work. I've tried numerous times to spawn a new instance with a different configuration, but it doesn't seem to work.

This is my cloud-config:
```yaml
#cloud-config

coreos:

  units:
  - name: etcd2.service
    command: start
  - name: fleet.service
    command: start

  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: https://discovery.etcd.io/<my actual token>

    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$public_ipv4:2380

    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://$public_ipv4:2379,http://$public_ipv4:4001
    listen-peer-urls: http://$public_ipv4:2380,http://$public_ipv4:7001

  fleet:
      public-ip: $public_ipv4
      metadata: "provider=digitalocean"

  update:
    reboot-strategy: best-effort
```

This is the error I'm getting when I run ```fleetctl list-machines```:
```
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
```

This is my output when I run ```ss -lnt```:
```
State       Recv-Q Send-Q                                             Local Address:Port                                                            Peer Address:Port              
LISTEN      0      128                                              188.226.196.230:7001                                                                       *:*                  
LISTEN      0      128                                              188.226.196.230:4001                                                                       *:*                  
LISTEN      0      128                                              188.226.196.230:2379                                                                       *:*                  
LISTEN      0      128                                                            *:5355                                                                       *:*                  
LISTEN      0      128                                              188.226.196.230:2380                                                                       *:*                  
LISTEN      0      128                                                           :::22                                                                        :::*                  
LISTEN      0      128                                                           :::5355                                                                      :::*
```
And when I run ```systemctl -l status etcd && systemctl -l status etcd2``` I get this:
```
● etcd.service - etcd
   Loaded: loaded (/usr/lib64/systemd/system/etcd.service; static; vendor preset: disabled)
   Active: inactive (dead)
```

When I run ```journalctl --unit etcd.service --no-pager``` I get this:
```
-- Logs begin at Fri 2015-08-07 13:49:28 UTC, end at Fri 2015-08-07 13:55:20 UTC. --
Failed to get journal fields: Cannot assign requested address
```

As I'm quite new to CoreOS I'm not sure where to look for problems and why it's failing to start etcd2.

**Comment by crawford** [comment]
The service is called etcd2.service. Run `systemctl status etcd2` instead.

**Comment by YP28** [comment]
When I run ```systemctl status etcd2``` this is the output:
```
core@core-01 ~ $ systemctl status etcd2
● etcd2.service - etcd2
   Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd2.service.d
           └─20-cloudinit.conf
   Active: active (running) since Fri 2015-08-07 16:28:12 UTC; 59s ago
 Main PID: 590 (etcd2)
   Memory: 11.2M
      CPU: 65ms
   CGroup: /system.slice/etcd2.service
           └─590 /usr/bin/etcd2

Aug 07 16:28:12 core-01 etcd2[590]: 2015/08/07 16:28:12 etcd: listening for peers on http://10.129.17.241:2380
Aug 07 16:28:12 core-01 etcd2[590]: 2015/08/07 16:28:12 etcd: listening for peers on http://10.129.17.241:7001
Aug 07 16:28:12 core-01 etcd2[590]: 2015/08/07 16:28:12 etcd: listening for client requests on http://0.0.0.0:2379
Aug 07 16:28:12 core-01 etcd2[590]: 2015/08/07 16:28:12 etcd: listening for client requests on http://0.0.0.0:4001
Aug 07 16:28:12 core-01 etcd2[590]: 2015/08/07 16:28:12 etcdserver: datadir is valid for the 2.0.1 format
Aug 07 16:28:17 core-01 etcd2[590]: 2015/08/07 16:28:17 discovery: during cluster status check connection to https://discovery.etcd.io timed out, retrying in 2s
Aug 07 16:28:23 core-01 etcd2[590]: 2015/08/07 16:28:23 discovery: found self 91b52b56c99fde64 in the cluster
Aug 07 16:28:23 core-01 etcd2[590]: 2015/08/07 16:28:23 discovery: found 1 peer(s), waiting for 2 more
Aug 07 16:29:06 core-01 etcd2[590]: 2015/08/07 16:29:06 discovery: found peer 6eb411b0f432a292 in the cluster
Aug 07 16:29:06 core-01 etcd2[590]: 2015/08/07 16:29:06 discovery: found 2 peer(s), waiting for 1 more
```

Apparently it's waiting for another node, even though I didn't define a number of nodes as I do not know how many I will add.

**Comment by YP28** [comment]
I added a 3rd node, and logged out and back in to the first node again it showed the right nodes when running ```fleetctl list-machines```. However, when I try to start a few services, it shows me the following error:
```
The authenticity of host '188.226.246.42' can't be established.
RSA key fingerprint is 97:bc:0a:b4:dd:87:88:f6:39:b1:26:0b:68:8a:4b:6c.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '188.226.246.42' (RSA) to the list of known hosts.
-- Logs begin at Fri 2015-08-07 16:35:28 UTC. --
Failed to get journal fields: Cannot assign requested address
```
So now it seems to login to the remote node correctly (I think), but that error shows up.

**Comment by crawford** [comment]
When creating a discovery token, you need to provide the size of the initial cluster (https://coreos.com/os/docs/latest/cluster-discovery.html).

The docker service is socket-activated, so until someone tries to connect to use it, it won't start.

**Comment by YP28** [comment]
Aah, that explains the docker service not running.

I did some more testing, and apparently something was wrong with my unit file that caused it to fail. I got confused because of the error messages though. Since it threw a handshake failure error at me while the problem was that there were not enough instances in the cluster.

**Comment by DJviolin** [comment]
Under CoreOS 884.0.0, I'm unable to start fleet. Here is my config file:

```
#cloud-config

coreos:
  etcd2:
    name: core-01
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/5997...
    # multi-region and multi-cloud deployments need to use $public_ipv4
    #advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    advertise-client-urls: http://$public_ipv4:2379,http://$public_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    initial-cluster-token: core-01_etcd
    initial-cluster: core-01=http://$private_ipv4:2380
    initial-cluster-state: new
  fleet:
    public-ip: $public_ipv4 # used for fleetctl ssh command
    metadata: region=lon1
  flannel:
    interface: $public_ipv4
  update:
    reboot-strategy: best-effort
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
ssh_authorized_keys:
  - ssh-rsa AAAA...
hostname: core-01
write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no

```
