### ISSUE TITLE
CoreOS bonding issue

### ISSUE THREAD

**Issue by jordannielsen** [coreos/bugs#445]
Having issues with bonding and coreos on the stable, beta, and alpha pxe images. Here is my cloud config

I am seeing the errors similar to those in the screen shot below. However, taking down and restarting doesn't fix the issue. This is on Dell r620 hardware with Intel 10Gb nics.  

![9263eafa-1f4c-11e4-8c18-56c70e829779](https://cloud.githubusercontent.com/assets/7017592/9412200/b19961c4-47e7-11e5-9095-addb1b4ba55d.png)

Below is my cloud-config file. 

```yaml
#cloud-config

hostname: kube-node03

coreos:
  units:
    - name: eno1.network
      runtime: true
      content: |
        [Match]
        Name=eno1
     
        [Network]
        Bond=bond0
    
    - name: eno2.network
      runtime: true
      content: |
        [Match]
        Name=eno2

        [Network]
        Bond=bond0
    
    - name: bond0.netdev
      runtime: true
      content: | 
        [NetDev]
        Name=bond0
        Kind=bond
    
    - name: bond0.network
      runtime: true
      content: |
        [Match]
        Name=bond0

        [Network]
        Address=10.10.10.10/23
        Gateway=10.10.10.1
     
    - name: systemd-networkd.service
      command: stop
    - name: down-interfaces.service
      command: start
      content: | 
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set eno3 down
        ExecStart=/usr/bin/ip addr flush dev eno3     
    - name: systemd-networkd.service
      command: start

    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start


ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC
```

Any thoughts if I am doing something wrong or if there is a work around for a bug I am hitting?

Thanks,

Jordan
