### ISSUE TITLE
on initial boot in 766.3.0, etcd2 is missing the environment variables supplied as drop-ins

### ISSUE THREAD

**Issue by danielschonfeld** [coreos/bugs#467]
On every single boot this happens for me since upgrading to 766.3.0 from 723.3.0.

Relevant cloud-config portion:
```
coreos:
  etcd2:
    name: master
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-cluster-token: k8s_etcd
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster: master=http://$private_ipv4:2380
    initial-cluster-state: new
```

When the machine boots up, the following environment variables are supplied to the etcd2 process:
```
$ sudo cat /proc/547/environ
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binHOME=/dev/nullLOGNAME=etcdUSER=etcdSHELL=/sbin/nologinETCD_DATA_DIR=/var/lib/etcd2ETCD_NAME=b73c5e73779a430db3adc026a336975f
```

Upon restart etcd utilizing `sudo systemctl restart etcd2`:
```
$ sudo cat /proc/1292/environ
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binHOME=/dev/nullLOGNAME=etcdUSER=etcdSHELL=/sbin/nologinETCD_DATA_DIR=/var/lib/etcd2ETCD_NAME=masterETCD_ELECTION_TIMEOUT=1200ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.4:2379,http://10.0.0.4:4001ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.4:2380ETCD_INITIAL_CLUSTER=master=http://10.0.0.4:2380ETCD_INITIAL_CLUSTER_STATE=newETCD_INITIAL_CLUSTER_TOKEN=k8s_etcdETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001ETCD_LISTEN_PEER_URLS=http://10.0.0.4:2380,http://10.0.0.4:7001
```

etcd2 journalctl logs tell the same story

**Comment by crawford** [comment]
It looks like etcd2 is starting before coreos-cloudinit. Have you enabled etcd2.service (at any point)?

**Comment by danielschonfeld** [comment]
@crawford yes i have

```
coreos:
  etcd2:
    name: master
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-cluster-token: k8s_etcd
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster: master=http://$private_ipv4:2380
    initial-cluster-state: new
  units:
    - name: etcd.service
      mask: true
    - name: fleet.service
      mask: true
    - name: ntpd.service
      command: restart
    - name: etcd2.service
      enable: true

```
