### ISSUE TITLE
[SOLVED] SSH Connection Refused after EC2 reboot of CoreOS instance

### ISSUE THREAD

**Issue by Dynom** [coreos/bugs#479]
Hi,

I've seen several topics on this matter, but none offers a solution to my problem. 

I've investigated the following things:
* Mount of drives, but I see no indication that this failed. However I have no idea how to debug this thoroughly
* sshd misconfiguration, but I see no indication that this is incorrect. The configuration files seem correct, no duplicate things, etc.

I've mounted the EBS of a broken instance on a running instance, and I've compared files. But as soon as I reboot a newly created instance, I'm unable to use the instance. I've use the HVM AMI from here: https://coreos.com/os/docs/latest/booting-on-ec2.html. I'm currently on 766.3.0.

A few assumptions:
* Since I get a "Connection Refused" instantly, I'm not looking at things like firewalling or AWS security policies. Mostly because they'll result in a certain delay (timeouts) when connecting. Also the AWS security policies are wide open (accept anything from anywhere).
* The CoreOS provider AMI is probably without bugs, although I did find some interesting lines in: `/usr/sbin/coreos-postinst`.

**Comment by Dynom** [comment]
*It's not so much solved, per se, but the work around:*

I've updated my `cloudconfig` definition to the bare necessities. And found out that not trying to change any SSH settings (either via re-writing `/etc/ssh/sshd_config` or define a `ssh.socket` unit) did the trick.

**Comment by crawford** [comment]
What options were you changing?

**Comment by Dynom** [comment]
Basically anything I tried resulted in a problem, but I tried to change the port.
```yaml
#cloud-config

coreos:
  units:
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2222
        Accept=yes
        FreeBind=true
```
