### ISSUE TITLE
Change the SSHD settings on a CoreOS installation on EC2

### ISSUE THREAD

**Issue by Dynom** [coreos/bugs#480]
Hello,

**TL;DR**
I'd like to change some SSH settings and I'm unsure on how to proceed. Whenever I follow this guide: https://coreos.com/os/docs/latest/customizing-sshd.html  (and I use the `sshd.socket` approach.) My EC2 instance won't survive a reboot (as outlined in issue #479).

**The longer version**
I've noticed that `sshd.socket` is started and loaded from `/usr/lib64/systemd/system/sshd.socket`. However this partition is mounted using a read-only partition:
```
$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   30G  0 disk
|-xvda1 202:1    0  128M  0 part /boot
|-xvda2 202:2    0    2M  0 part
|-xvda3 202:3    0    1G  0 part /usr
|-xvda4 202:4    0    1G  0 part
|-xvda6 202:6    0  128M  0 part /usr/share/oem
|-xvda7 202:7    0   64M  0 part
`-xvda9 202:9    0 27.7G  0 part /
```
```
$ mount | grep xvda3
/dev/xvda3 on /usr type ext4 (ro,relatime)
```

Example cloud-config:
```
#cloud-config

coreos:
  units:
  - name: sshd.socket
    command: restart
    content: |
      [Socket]
      ListenStream=2222
      Accept=yes
```

**Comment by vcaputo** [comment]
coreos-cloudinit will write configured units to /etc/systemd/system or /run/systemd/system, which take precedence over what's found in /usr/lib/systemd/system.

As for your problem, can you post the console output of the failed boot?

**Comment by Dynom** [comment]
Unfortunately no, since I'm no longer to access the machine.

Mounting the disks to another instance to inspect was also fairly fruitless. What I did see, however, is that `/etc/systemd/system/sshd.sock` was written, with the contents specified in the cloud-config. But apparently that results in an sshd that fails to start.

**Comment by Dynom** [comment]
Reproducing the problem is fairly simple, if you have an AWS account.

**The steps**
 1. Pick a HVM AMI from here: https://coreos.com/os/docs/latest/booting-on-ec2.html (don't click launch, just click on the AMI link)
 2. Paste the cloud-config snippet (below this list) at the *Advanced section* at step 3 (*Configure Instance Details*) in the EC2 wizard. The config is the default snippet mentioned on the CoreOS page, with the added SSHD config.
 3. Specify a liberal Security policy at step 6 (*Configure Security Group*). I picked allow `all trafic` from `anywhere`. And ignore the justified warning, for this test-case.
 4. Wait until the machine is provisioned and reboot the instance (I've tried either the console and via the cli `sudo shutdown -r now`), then 
 5. Try to login via SSH `ssh core@<hostname> -p 2222` and behold the misery, neither the default port 22 or the newly specified port 2222 will allow you to connect.

**The Cloud config snippet**
```yaml
#cloud-config

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/<token>
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2222
        Accept=yes
```

**Notes**
* The SSHD config came from: https://coreos.com/os/docs/latest/customizing-sshd.html
