### ISSUE TITLE
Failed to start cloud-config

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#661]
<a href="https://github.com/rahulgopan"><img src="https://avatars.githubusercontent.com/u/7299162?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rahulgopan](https://github.com/rahulgopan)**
_Friday Sep 19, 2014 at 07:35 GMT_
_Originally opened as https://github.com/coreos/init/issues/130_

----

I get the following error at start up

"Failed to star Load config /var/lib/coreos-install/user_data"

And also,

Failed Units: 1
  user-cloudinit@var-lib-coreos\x2dinstall-user_data.service

Where am i getting it wrong??

**Comment by crawford** [comment]
<a href="https://github.com/rahulgopan"><img src="https://avatars.githubusercontent.com/u/7299162?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rahulgopan](https://github.com/rahulgopan)**
_Friday Sep 19, 2014 at 07:40 GMT_

----

YAML file 

```yaml
#cloud-config

hostname:coreos3

coreos:
 units:
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
 etcd:
   discovery: https://discovery.etcd.io/f522332095fb782bb515dcc163c37bd9
```
