### ISSUE TITLE
No IP data in cloudinit on OpenStack

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#67]
From: https://github.com/coreos/init/pull/105#issuecomment-48544566

This is on Ubuntu 14.04 Icehouse OpenStack using the alpha channel OpenStack image (367.0.0). This image was not pulling IPs from "/media/configdrive/ec2/latest/meta-data.json" by default but the IP address data is there.

I'm going to give the Rackspace image a try since config drive is providing the right meta data.

When looking at "/run/systemd/system/etcd.service.d/20-cloudinit.service", IP addresses are blank. The rest of the information matches what's in my cloud-config.yaml file. The only reference I could find to this file is nova-agent-watcher. I was attempting to restart coreos-setup-environment via a unit in my cloud-config.yaml file.

/run/systemd/system/etcd.service.d/20-cloudinit.service

```
[Service]
Environment="ETCD_ADDR=:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/ecbeca419c1cc8d561b9db99b1696acf"
Environment="ETCD_NAME=7ddac4be86324214856fc2635f0abd69"
Environment="ETCD_PEER_ADDR=:7001"
```

```
#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/ecbeca419c1cc8d561b9db99b1696acf
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
```
