### ISSUE TITLE
hostname and machine-id for etcd section

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#710]
<a href="https://github.com/polvi"><img src="https://avatars.githubusercontent.com/u/46035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [polvi](https://github.com/polvi)**
_Tuesday Mar 18, 2014 at 01:12 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/30_

----

$hostname and $machine_id should be a valid substitutions for the etcd section. coreos.etcd.name should default to $hostname unless specificed. Cloudinit should make sure it runs its own hostname code early so that value will apply. $hostname should be the same as the result of the hostname() system call. $machine-id should be the value in /etc/machine-id.

**Comment by crawford** [comment]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bcwaldon](https://github.com/bcwaldon)**
_Tuesday Mar 18, 2014 at 20:09 GMT_

----

Most of this functionality is now implemented. The substitutions, however, are not.

**Comment by crawford** [comment]
<a href="https://github.com/polvi"><img src="https://avatars.githubusercontent.com/u/46035?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [polvi](https://github.com/polvi)**
_Tuesday Mar 18, 2014 at 20:12 GMT_

----

huh? only the defaults are?

**Comment by crawford** [comment]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bcwaldon](https://github.com/bcwaldon)**
_Tuesday Mar 18, 2014 at 20:13 GMT_

----

The behavior of defaulting the name to machine-id then to hostname is implemented. The ability for a user to put $hostname or $machine-id in their cloud-config is not implemented.

**Comment by crawford** [comment]
<a href="https://github.com/polvi"><img src="https://avatars.githubusercontent.com/u/46035?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [polvi](https://github.com/polvi)**
_Tuesday Mar 18, 2014 at 20:14 GMT_

----

ok

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Tuesday Jan 20, 2015 at 22:20 GMT_

----

@polvi do you still want this feature (one year later...)? The hostname substitution is going to be racy, but machine_id might be useful (though I haven't heard anyone else ask for it).

**Comment by crawford** [comment]
<a href="https://github.com/chansn"><img src="https://avatars.githubusercontent.com/u/9049168?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chansn](https://github.com/chansn)**
_Saturday Feb 07, 2015 at 02:02 GMT_

----

if its for etcd, then %H will work, as it gets resolved by systemd. We use it here for a generic cloud-init. Only slight annoyance is that the new etcd 2.0 params are ignored, so we just feed them to an extra unit file under etcd.service.

Example:
``` yaml
#cloud-config

coreos:
  etcd:
    name: "%H"
    data-dir: /var/etcd/data
  fleet:
    etcd-servers: http://%H:2379
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
write_files:
  - path: /run/systemd/system/etcd.service.d/10-param.conf
    permissions: 0644
    content: |
      [Service]
      Environment=ETCD_ADVERTISE_CLIENT_URLS=http://%H:2379
      Environment=ETCD_LISTEN_CLIENT_URLS=http://%H:2379
      Environment=ETCD_LISTEN_PEER_URLS=http://%H:2380
```
