### ISSUE TITLE
Parameter for setting group ID for update service

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#715]
<a href="https://github.com/robszumski"><img src="https://avatars.githubusercontent.com/u/755540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [robszumski](https://github.com/robszumski)**
_Friday Mar 21, 2014 at 22:19 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/47_

----

Something like:

```
#cloud-config

coreos:
  updates:
    groupId: <uuid>
    server: <hostname>
```
