### ISSUE TITLE
Support 'mask' in coreos.units

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#716]
<a href="https://github.com/robszumski"><img src="https://avatars.githubusercontent.com/u/755540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [robszumski](https://github.com/robszumski)**
_Thursday Mar 27, 2014 at 18:58 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/54_

----

Supporting `mask` makes it easy to inhibit auto reboots:

```
coreos:
    units:
      - name: update-engine-reboot-manager.service
        command: mask
      - name: update-engine-reboot-manager.service
        command: stop
```
