### ISSUE TITLE
Need option to install, but not enable, unit files.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#722]
<a href="https://github.com/apatil"><img src="https://avatars.githubusercontent.com/u/52041?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [apatil](https://github.com/apatil)**
_Thursday Apr 10, 2014 at 18:19 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/69_

----

Say I want to create a template service, `db@.service`, whose instances restart automatically after CoreOS' automatic reboots. The way to do that is to add `WantedBy=multi-user.target` to the install section, so that `systemctl enable db@1` results in a symlink to `db@1` being created in `multi-user.target.wants`. 

I create a user data document like so:

```yaml
#cloud-config

coreos:
  units:
    - name: db@.service
      content: |
        [Service] 
        ... 
        [Install]
        WantedBy=multi-user.target
```

and install it with coreos-cloudinit. Currently, the unit is automatically enabled, which results in a symlink to `db@.service` being placed in `multi-user.target.wants`. When the machine reboots, an unwanted service called `db@multi-user.service` is started automatically.
