### ISSUE TITLE
feat(*): formalize support for drop-in configs

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#732]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jonboulle](https://github.com/jonboulle)**
_Thursday May 15, 2014 at 02:02 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/108_

----

The ability for units to be drop-in was added in https://github.com/coreos/coreos-cloudinit/commit/31cfad91e301d01bfe805355c05cb07920093edc , but prevented from being exposed through cloud-config in https://github.com/coreos/coreos-cloudinit/commit/cdee32d24585b59b84bd4c7e7c0b597065a29526 because there are unclear semantics around how they should work with multiple invocations of cloud-config. Figure this out and expose drop-in units to the user.

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Thursday May 15, 2014 at 02:32 GMT_

----

It is a little more verbose than a boolean but the config and actual behavior map a little better:
```
coreos:
    units:
      - name: docker.service
        command: restart
        dropin:
          - name: 20-proxy.conf
            content: HTTP_PROXY=foo
```

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Thursday May 15, 2014 at 02:50 GMT_

----

Devil's advocate, why duplicate the name/content fields at all?

What about just having the drop-in field be a string: if unset, normal config file, else, drop-in using that string as drop-in name.

```
coreos:
    units:
      - name: docker.service
        command: restart
        dropin: 20-proxy.conf
        content: HTTP_PROXY=foo
```
