### ISSUE TITLE
Support for submitting fleet units

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#750]
<a href="https://github.com/hackzilla"><img src="https://avatars.githubusercontent.com/u/1474182?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hackzilla](https://github.com/hackzilla)**
_Wednesday Jul 09, 2014 at 08:08 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/175_

----

I'd love to see defining which units to use within user-data file.

At the moment it seems to be a manual step.

```
coreos:
  fleet:
      units:
        - unit: ping.service
          start: yes
        - unit: pong.service
          start: yes
```
