### ISSUE TITLE
Inadvertent change in 0.11.1?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#779]
<a href="https://github.com/marclennox"><img src="https://avatars.githubusercontent.com/u/651620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marclennox](https://github.com/marclennox)**
_Thursday Nov 20, 2014 at 20:40 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/264_

----

I've noticed a change in behaviour in coreos-cloudinit after my servers upgraded from coreos 494 to 505.

I have my own cloud-config server that my machines use to pull their configuration.  The cloud config is pieced together on this server from multiple modular pieces into a single configuration file, the end result being a configuration with multiple root nodes for (write-files, coreos, etc.).

While this may not be valid YAML, before 0.11.1 it would process all the entries no issue, but with 0.11.1 it appears that, with the "coreos" nodes only, it only processes the last one found in the config.  Multiple "write-files" nodes appear to still be working fine.

Is this expected?

**Comment by crawford** [comment]
<a href="https://github.com/marclennox"><img src="https://avatars.githubusercontent.com/u/651620?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marclennox](https://github.com/marclennox)**
_Thursday Nov 20, 2014 at 20:41 GMT_

----

As a side note, I'm guessing that Digital Ocean CoreOS instances were affected by this problem also, because after upgrading to 505 my servers lost their IPv4 network access.  Luckily I was able to SFTP into them through the private IPv6 address and retrieve stuff.

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Thursday Nov 20, 2014 at 20:48 GMT_

----

Can you show me an example of the final config?

**Comment by crawford** [comment]
<a href="https://github.com/marclennox"><img src="https://avatars.githubusercontent.com/u/651620?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marclennox](https://github.com/marclennox)**
_Thursday Nov 20, 2014 at 20:57 GMT_

----

Will do in a few hours.  I'm also going to look at Digital Oceans oem cloud config.  Almost certain this issue has broken their network service config 

—

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Thursday Nov 20, 2014 at 21:42 GMT_

----

I haven't seen any issues with DigitalOcean. Even if cloudinit encounters an invalid cloud-config, it should still set up the network. Do you still have the configuration for the instance that lost its network?

**Comment by crawford** [comment]
<a href="https://github.com/marclennox"><img src="https://avatars.githubusercontent.com/u/651620?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marclennox](https://github.com/marclennox)**
_Thursday Nov 20, 2014 at 22:03 GMT_

----

OK, I see why mine went down, it's because I appended an additional coreos: node onto the oem cloud-config (a temporary hack)...  but the issue is clearly that multiple coreos nodes in the config are being ignored (except the last).  Here's my (redacted) oem cloud config.  The second hacked coreos node is clobbering the first one which sets up the public network.

This worked fine prior to 0.11.1

```yml
#cloud-config

coreos:
    units:
      - name: 99-public-interface.network
        runtime: yes
        content: |
          [Match]
          Path=*:03.0

          [Network]
          IPv4LL=true
      - name: systemd-networkd.service
        command: restart
      - name: oem-cloudinit.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from DigitalOcean metadata

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/coreos-cloudinit --from-digitalocean-metadata=http://169.254.169.254/ --convert-netconf=digitalocean
    oem:
      id: digitalocean
      name: DigitalOcean
      home-url: https://www.digitalocean.com/
      bug-report-url: https://github.com/coreos/bugs/issues

# Replacement for initial user-data
write_files:
  - path: /run/user/cloud-config.env
    owner: root
    permissions: 0644
    content: |
      CLOUD_CONFIG_URI=https://[REDACTED]/cloud-config
coreos:
  units:
    - name: user-cloudinit-2.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        Description=Cloudinit from user metadata service
        [Service]
        Type=oneshot
        EnvironmentFile=/run/user/cloud-config.env
        EnvironmentFile=-/run/user/cloud-config.local.env
        ExecStartPre=/usr/bin/wget -S -O /run/user/cloud-config.yml ${CLOUD_CONFIG_URI}
        ExecStart=/usr/bin/coreos-cloudinit --from-file=/run/user/cloud-config.yml
```

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Thursday Nov 20, 2014 at 23:22 GMT_

----

I'm really surprised this ever worked since it's not valid YAML. As you suspected, if you send your config through a YAML linter, it will return:

```yaml
coreos: 
  units: 
    - 
      command: restart
      content: |-
          [Unit]
          Description=Cloudinit from user metadata service
          [Service]
          Type=oneshot
          EnvironmentFile=/run/user/cloud-config.env
          EnvironmentFile=-/run/user/cloud-config.local.env
          ExecStartPre=/usr/bin/wget -S -O /run/user/cloud-config.yml ${CLOUD_CONFIG_URI}
          ExecStart=/usr/bin/coreos-cloudinit --from-file=/run/user/cloud-config.yml
      name: user-cloudinit-2.service
      runtime: true
write_files: 
  - 
    content: "CLOUD_CONFIG_URI=https://[REDACTED]/cloud-config\n"
    owner: root
    path: /run/user/cloud-config.env
    permissions: 420
```

To answer you question, yes this new behavior is expected. It was the old behavior which was unexpected.
