### ISSUE TITLE
User doesn't get added to portage & systemd-journal groups

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#780]
<a href="https://github.com/digital-wonderland"><img src="https://avatars.githubusercontent.com/u/2522615?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [digital-wonderland](https://github.com/digital-wonderland)**
_Wednesday Nov 26, 2014 at 19:41 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/270_

----

I have a ```users:``` section like the following:

```
users:
  - name: stephan
    passwd: $MY_PWD
    groups:
      - docker
      - portage
      - sudo
      - systemd-journal
    ssh-authorized-keys:
      - ssh-rsa $MY_KEY
```

The user gets properly created, pwd & ssh key are properly set but the user only gets added to ```sudo```, ```docker``` & ```stephan``` but not to ```portage``` & ```systemd-journal```.

Also I'm missing references for those within ```/etc/group```:

```
# cat /etc/group
wheel:x:10:root,core
sudo:x:150:stephan
docker:x:233:core,stephan
stephan:x:1000:
```

This is with CoreOS 509.1.0
