### ISSUE TITLE
File encodings with base64 data aren't handled correctly

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#789]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [crawford](https://github.com/crawford)**
_Tuesday Jan 13, 2015 at 02:19 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/296_

----

The YAML parser appears to be silently decoding base64 data. If the user explictly declares the data to be base64, it's run through the decoder a second time causing a failure.

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Tuesday Jan 13, 2015 at 03:09 GMT_

----

These are equivalent.
```yaml
write_files:
 - path: /tmp/a
    content: SGVsbG8hCg==
    encoding: base64

  - path: /tmp/b
    content: !!binary SGVsbG8hCg==
```
