### ISSUE TITLE
validator shows incorrect line number for invalid binary data

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#800]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [crawford](https://github.com/crawford)**
_Friday Feb 27, 2015 at 03:19 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/323_

---

``` yaml
#cloud-config
write_files:
  - encoding: gzip
    content: !!binary |
      abc
```

```
bin/coreos-cloudinit --validate --from-file a
Checking availability of "local-file"
Fetching user-data from datasource of type "local-file"
line 1: error: !!binary value contains invalid base64 data
line 0: warning: incorrect type for "" (want struct)
```
