### ISSUE TITLE
nova-agent-watcher overwrites cloud-config fleet config

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#867]
<a href="https://github.com/anguslees"><img src="https://avatars.githubusercontent.com/u/224224?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anguslees](https://github.com/anguslees)**
_Friday Sep 19, 2014 at 05:15 GMT_
_Originally opened as https://github.com/coreos/nova-agent-watcher/issues/11_

---

(Probably related to https://github.com/coreos/nova-agent-watcher/issues/6)

On rackspace, I have a cloud-config that says:

```
coreos:
  fleet:
    public-ip: $private_ipv4
    metadata: foo=bar
```

but I'm often seeing a /run/systemd/system/fleet.service.d/20-cloudinit.conf that looks like:

```
[Service]
Environment="FLEET_AUTOSTART=false"
```

I think I've tracked this down to a race between nova-agent-watcher.service and user-configdrive.service.  If the latter runs last, I get the correct 20-cloudinit.conf

For reference, nova-agent-watcher seems to generate/use a bunch of /tmp/rackspace-cloudinit-XXXX files, that look like trivial stubs like:

```
#cloud-config
ssh_authorized_keys: []
 coreos:
  etcd: {}
  fleet:
    autostart: false
  units:
  - name: 50-eth2.network
    runtime: false
    content: '[Match]
```

... I'm guessing that fleet block is causing coreos-cloudinit to trash the 20-cloudinit.conf file.

(This is on CoreOS 440.0.0)
