### ISSUE TITLE
coreos-cloud-init: Support comma separated groups because of cloud-init bug

### ISSUE THREAD

**Issue by pquerna** [coreos/bugs#963]
Current versions of `cloud-init` used by other distributions have a bug with adding users with groups:

https://bugs.launchpad.net/cloud-init/+bug/1356208

This basically means the only **working** method of adding groups to a user on creation is to comma separate them.

Unfortunately, CoreOS cloud-init only supports the array syntax.

Works with normal cloud-init, but not CoreOS cloud-init:
```yaml
#cloud-config

users:
- name: paul.querna
  shell: /bin/bash
  groups: sudo,docker
```

Doesn't work with normal cloud-init, but works with CoreOS cloud-init:
```yaml
#cloud-config

users:
- name: paul.querna
  shell: /bin/bash
  groups: [sudo, docker]
```

I'd like for CoreOS cloud-init to support the comma syntax, so that a single syntax at least works in both with both implementations.

CC @crawford
